
import { ScriptType, KanaLine, Mora, Word, KanaSimilarities } from './types';

// MORA_DATA: Comprehensive list of kana characters
export const MORA_DATA: { [key: string]: Mora } = {
  // Hiragana Basic
  'あ': { kana: 'あ', romaji: 'a', type: 'basic', script: ScriptType.Hiragana, consonant: '', vowel: 'a' },
  'い': { kana: 'い', romaji: 'i', type: 'basic', script: ScriptType.Hiragana, consonant: '', vowel: 'i' },
  'う': { kana: 'う', romaji: 'u', type: 'basic', script: ScriptType.Hiragana, consonant: '', vowel: 'u' },
  'え': { kana: 'え', romaji: 'e', type: 'basic', script: ScriptType.Hiragana, consonant: '', vowel: 'e' },
  'お': { kana: 'お', romaji: 'o', type: 'basic', script: ScriptType.Hiragana, consonant: '', vowel: 'o' },
  'か': { kana: 'か', romaji: 'ka', type: 'basic', script: ScriptType.Hiragana, consonant: 'k', vowel: 'a' },
  'き': { kana: 'き', romaji: 'ki', type: 'basic', script: ScriptType.Hiragana, consonant: 'k', vowel: 'i' },
  'く': { kana: 'く', romaji: 'ku', type: 'basic', script: ScriptType.Hiragana, consonant: 'k', vowel: 'u' },
  'け': { kana: 'け', romaji: 'ke', type: 'basic', script: ScriptType.Hiragana, consonant: 'k', vowel: 'e' },
  'こ': { kana: 'こ', romaji: 'ko', type: 'basic', script: ScriptType.Hiragana, consonant: 'k', vowel: 'o' },
  'さ': { kana: 'さ', romaji: 'sa', type: 'basic', script: ScriptType.Hiragana, consonant: 's', vowel: 'a' },
  'し': { kana: 'し', romaji: 'shi', type: 'basic', script: ScriptType.Hiragana, consonant: 'sh', vowel: 'i' },
  'す': { kana: 'す', romaji: 'su', type: 'basic', script: ScriptType.Hiragana, consonant: 's', vowel: 'u' },
  'せ': { kana: 'せ', romaji: 'se', type: 'basic', script: ScriptType.Hiragana, consonant: 's', vowel: 'e' },
  'そ': { kana: 'そ', romaji: 'so', type: 'basic', script: ScriptType.Hiragana, consonant: 's', vowel: 'o' },
  'た': { kana: 'た', romaji: 'ta', type: 'basic', script: ScriptType.Hiragana, consonant: 't', vowel: 'a' },
  'ち': { kana: 'ち', romaji: 'chi', type: 'basic', script: ScriptType.Hiragana, consonant: 'ch', vowel: 'i' },
  'つ': { kana: 'つ', romaji: 'tsu', type: 'basic', script: ScriptType.Hiragana, consonant: 'ts', vowel: 'u' },
  'て': { kana: 'て', romaji: 'te', type: 'basic', script: ScriptType.Hiragana, consonant: 't', vowel: 'e' },
  'と': { kana: 'と', romaji: 'to', type: 'basic', script: ScriptType.Hiragana, consonant: 't', vowel: 'o' },
  'な': { kana: 'な', romaji: 'na', type: 'basic', script: ScriptType.Hiragana, consonant: 'n', vowel: 'a' },
  'に': { kana: 'に', romaji: 'ni', type: 'basic', script: ScriptType.Hiragana, consonant: 'n', vowel: 'i' },
  'ぬ': { kana: 'ぬ', romaji: 'nu', type: 'basic', script: ScriptType.Hiragana, consonant: 'n', vowel: 'u' },
  'ね': { kana: 'ね', romaji: 'ne', type: 'basic', script: ScriptType.Hiragana, consonant: 'n', vowel: 'e' },
  'の': { kana: 'の', romaji: 'no', type: 'basic', script: ScriptType.Hiragana, consonant: 'n', vowel: 'o' },
  'は': { kana: 'は', romaji: 'ha', type: 'basic', script: ScriptType.Hiragana, consonant: 'h', vowel: 'a', particleRomaji: 'wa' },
  'ひ': { kana: 'ひ', romaji: 'hi', type: 'basic', script: ScriptType.Hiragana, consonant: 'h', vowel: 'i' },
  'ふ': { kana: 'ふ', romaji: 'fu', type: 'basic', script: ScriptType.Hiragana, consonant: 'f', vowel: 'u' },
  'へ': { kana: 'へ', romaji: 'he', type: 'basic', script: ScriptType.Hiragana, consonant: 'h', vowel: 'e', particleRomaji: 'e' },
  'ほ': { kana: 'ほ', romaji: 'ho', type: 'basic', script: ScriptType.Hiragana, consonant: 'h', vowel: 'o' },
  'ま': { kana: 'ま', romaji: 'ma', type: 'basic', script: ScriptType.Hiragana, consonant: 'm', vowel: 'a' },
  'み': { kana: 'み', romaji: 'mi', type: 'basic', script: ScriptType.Hiragana, consonant: 'm', vowel: 'i' },
  'む': { kana: 'む', romaji: 'mu', type: 'basic', script: ScriptType.Hiragana, consonant: 'm', vowel: 'u' },
  'め': { kana: 'め', romaji: 'me', type: 'basic', script: ScriptType.Hiragana, consonant: 'm', vowel: 'e' },
  'も': { kana: 'も', romaji: 'mo', type: 'basic', script: ScriptType.Hiragana, consonant: 'm', vowel: 'o' },
  'や': { kana: 'や', romaji: 'ya', type: 'basic', script: ScriptType.Hiragana, consonant: 'y', vowel: 'a' },
  'ゆ': { kana: 'ゆ', romaji: 'yu', type: 'basic', script: ScriptType.Hiragana, consonant: 'y', vowel: 'u' },
  'よ': { kana: 'よ', romaji: 'yo', type: 'basic', script: ScriptType.Hiragana, consonant: 'y', vowel: 'o' },
  'ら': { kana: 'ら', romaji: 'ra', type: 'basic', script: ScriptType.Hiragana, consonant: 'r', vowel: 'a' },
  'り': { kana: 'り', romaji: 'ri', type: 'basic', script: ScriptType.Hiragana, consonant: 'r', vowel: 'i' },
  'る': { kana: 'る', romaji: 'ru', type: 'basic', script: ScriptType.Hiragana, consonant: 'r', vowel: 'u' },
  'れ': { kana: 'れ', romaji: 're', type: 'basic', script: ScriptType.Hiragana, consonant: 'r', vowel: 'e' },
  'ろ': { kana: 'ろ', romaji: 'ro', type: 'basic', script: ScriptType.Hiragana, consonant: 'r', vowel: 'o' },
  'わ': { kana: 'わ', romaji: 'wa', type: 'basic', script: ScriptType.Hiragana, consonant: 'w', vowel: 'a' },
  'を': { kana: 'を', romaji: 'o', type: 'basic', script: ScriptType.Hiragana, consonant: 'w', vowel: 'o', particleRomaji: 'o' },
  'ん': { kana: 'ん', romaji: 'n', type: 'n_syllabic', script: ScriptType.Hiragana, consonant: 'n', vowel: '' },

  // Hiragana Dakuten (Voiced)
  'が': { kana: 'が', romaji: 'ga', type: 'basic-d', baseKana: 'か', script: ScriptType.Hiragana, consonant: 'g', vowel: 'a' },
  'ぎ': { kana: 'ぎ', romaji: 'gi', type: 'basic-d', baseKana: 'き', script: ScriptType.Hiragana, consonant: 'g', vowel: 'i' },
  'ぐ': { kana: 'ぐ', romaji: 'gu', type: 'basic-d', baseKana: 'く', script: ScriptType.Hiragana, consonant: 'g', vowel: 'u' },
  'げ': { kana: 'げ', romaji: 'ge', type: 'basic-d', baseKana: 'け', script: ScriptType.Hiragana, consonant: 'g', vowel: 'e' },
  'ご': { kana: 'ご', romaji: 'go', type: 'basic-d', baseKana: 'こ', script: ScriptType.Hiragana, consonant: 'g', vowel: 'o' },
  'ざ': { kana: 'ざ', romaji: 'za', type: 'basic-d', baseKana: 'さ', script: ScriptType.Hiragana, consonant: 'z', vowel: 'a' },
  'じ': { kana: 'じ', romaji: 'ji', type: 'basic-d', baseKana: 'し', script: ScriptType.Hiragana, consonant: 'j', vowel: 'i' },
  'ず': { kana: 'ず', romaji: 'zu', type: 'basic-d', baseKana: 'す', script: ScriptType.Hiragana, consonant: 'z', vowel: 'u' },
  'ぜ': { kana: 'ぜ', romaji: 'ze', type: 'basic-d', baseKana: 'せ', script: ScriptType.Hiragana, consonant: 'z', vowel: 'e' },
  'ぞ': { kana: 'ぞ', romaji: 'zo', type: 'basic-d', baseKana: 'そ', script: ScriptType.Hiragana, consonant: 'z', vowel: 'o' },
  'だ': { kana: 'だ', romaji: 'da', type: 'basic-d', baseKana: 'た', script: ScriptType.Hiragana, consonant: 'd', vowel: 'a' },
  'ぢ': { kana: 'ぢ', romaji: 'ji', type: 'basic-d', baseKana: 'ち', script: ScriptType.Hiragana, consonant: 'j', vowel: 'i' },
  'づ': { kana: 'づ', romaji: 'zu', type: 'basic-d', baseKana: 'つ', script: ScriptType.Hiragana, consonant: 'z', vowel: 'u' },
  'で': { kana: 'で', romaji: 'de', type: 'basic-d', baseKana: 'て', script: ScriptType.Hiragana, consonant: 'd', vowel: 'e' },
  'ど': { kana: 'ど', romaji: 'do', type: 'basic-d', baseKana: 'と', script: ScriptType.Hiragana, consonant: 'd', vowel: 'o' },
  'ば': { kana: 'ば', romaji: 'ba', type: 'basic-d', baseKana: 'は', script: ScriptType.Hiragana, consonant: 'b', vowel: 'a' },
  'び': { kana: 'び', romaji: 'bi', type: 'basic-d', baseKana: 'ひ', script: ScriptType.Hiragana, consonant: 'b', vowel: 'i' },
  'ぶ': { kana: 'ぶ', romaji: 'bu', type: 'basic-d', baseKana: 'ふ', script: ScriptType.Hiragana, consonant: 'b', vowel: 'u' },
  'べ': { kana: 'べ', romaji: 'be', type: 'basic-d', baseKana: 'へ', script: ScriptType.Hiragana, consonant: 'b', vowel: 'e' },
  'ぼ': { kana: 'ぼ', romaji: 'bo', type: 'basic-d', baseKana: 'ほ', script: ScriptType.Hiragana, consonant: 'b', vowel: 'o' },

  // Hiragana Handakuten (P-sound)
  'ぱ': { kana: 'ぱ', romaji: 'pa', type: 'basic-hp', baseKana: 'は', script: ScriptType.Hiragana, consonant: 'p', vowel: 'a' },
  'ぴ': { kana: 'ぴ', romaji: 'pi', type: 'basic-hp', baseKana: 'ひ', script: ScriptType.Hiragana, consonant: 'p', vowel: 'i' },
  'ぷ': { kana: 'ぷ', romaji: 'pu', type: 'basic-hp', baseKana: 'ふ', script: ScriptType.Hiragana, consonant: 'p', vowel: 'u' },
  'ぺ': { kana: 'ぺ', romaji: 'pe', type: 'basic-hp', baseKana: 'へ', script: ScriptType.Hiragana, consonant: 'p', vowel: 'e' },
  'ぽ': { kana: 'ぽ', romaji: 'po', type: 'basic-hp', baseKana: 'ほ', script: ScriptType.Hiragana, consonant: 'p', vowel: 'o' },

  // Hiragana Small Yōon Vowels
  'ゃ': { kana: 'ゃ', romaji: 'ya', type: 'youon-y', script: ScriptType.Hiragana, vowel: 'a' },
  'ゅ': { kana: 'ゅ', romaji: 'yu', type: 'youon-y', script: ScriptType.Hiragana, vowel: 'u' },
  'ょ': { kana: 'ょ', romaji: 'yo', type: 'youon-y', script: ScriptType.Hiragana, vowel: 'o' },
  'ゎ': { kana: 'ゎ', romaji: 'wa', type: 'youon-w', script: ScriptType.Hiragana, vowel: 'a' }, // Less common

  // Hiragana Yōon (Contracted sounds) - K-line + y
  'きゃ': { kana: 'きゃ', romaji: 'kya', type: 'youon-y', constituentKana: ['き', 'ゃ'], script: ScriptType.Hiragana, consonant: 'ky', vowel: 'a' },
  'きゅ': { kana: 'きゅ', romaji: 'kyu', type: 'youon-y', constituentKana: ['き', 'ゅ'], script: ScriptType.Hiragana, consonant: 'ky', vowel: 'u' },
  'きょ': { kana: 'きょ', romaji: 'kyo', type: 'youon-y', constituentKana: ['き', 'ょ'], script: ScriptType.Hiragana, consonant: 'ky', vowel: 'o' },
  // Sh-line + y
  'しゃ': { kana: 'しゃ', romaji: 'sha', type: 'youon-y', constituentKana: ['し', 'ゃ'], script: ScriptType.Hiragana, consonant: 'sh', vowel: 'a' },
  'しゅ': { kana: 'しゅ', romaji: 'shu', type: 'youon-y', constituentKana: ['し', 'ゅ'], script: ScriptType.Hiragana, consonant: 'sh', vowel: 'u' },
  'しょ': { kana: 'しょ', romaji: 'sho', type: 'youon-y', constituentKana: ['し', 'ょ'], script: ScriptType.Hiragana, consonant: 'sh', vowel: 'o' },
  // Ch-line + y
  'ちゃ': { kana: 'ちゃ', romaji: 'cha', type: 'youon-y', constituentKana: ['ち', 'ゃ'], script: ScriptType.Hiragana, consonant: 'ch', vowel: 'a' },
  'ちゅ': { kana: 'ちゅ', romaji: 'chu', type: 'youon-y', constituentKana: ['ち', 'ゅ'], script: ScriptType.Hiragana, consonant: 'ch', vowel: 'u' },
  'ちょ': { kana: 'ちょ', romaji: 'cho', type: 'youon-y', constituentKana: ['ち', 'ょ'], script: ScriptType.Hiragana, consonant: 'ch', vowel: 'o' },
  // N-line + y
  'にゃ': { kana: 'にゃ', romaji: 'nya', type: 'youon-y', constituentKana: ['に', 'ゃ'], script: ScriptType.Hiragana, consonant: 'ny', vowel: 'a' },
  'にゅ': { kana: 'にゅ', romaji: 'nyu', type: 'youon-y', constituentKana: ['に', 'ゅ'], script: ScriptType.Hiragana, consonant: 'ny', vowel: 'u' },
  'にょ': { kana: 'にょ', romaji: 'nyo', type: 'youon-y', constituentKana: ['に', 'ょ'], script: ScriptType.Hiragana, consonant: 'ny', vowel: 'o' },
  // H-line + y
  'ひゃ': { kana: 'ひゃ', romaji: 'hya', type: 'youon-y', constituentKana: ['ひ', 'ゃ'], script: ScriptType.Hiragana, consonant: 'hy', vowel: 'a' },
  'ひゅ': { kana: 'ひゅ', romaji: 'hyu', type: 'youon-y', constituentKana: ['ひ', 'ゅ'], script: ScriptType.Hiragana, consonant: 'hy', vowel: 'u' },
  'ひょ': { kana: 'ひょ', romaji: 'hyo', type: 'youon-y', constituentKana: ['ひ', 'ょ'], script: ScriptType.Hiragana, consonant: 'hy', vowel: 'o' },
  // M-line + y
  'みゃ': { kana: 'みゃ', romaji: 'mya', type: 'youon-y', constituentKana: ['み', 'ゃ'], script: ScriptType.Hiragana, consonant: 'my', vowel: 'a' },
  'みゅ': { kana: 'みゅ', romaji: 'myu', type: 'youon-y', constituentKana: ['み', 'ゅ'], script: ScriptType.Hiragana, consonant: 'my', vowel: 'u' },
  'みょ': { kana: 'みょ', romaji: 'myo', type: 'youon-y', constituentKana: ['み', 'ょ'], script: ScriptType.Hiragana, consonant: 'my', vowel: 'o' },
  // R-line + y
  'りゃ': { kana: 'りゃ', romaji: 'rya', type: 'youon-y', constituentKana: ['り', 'ゃ'], script: ScriptType.Hiragana, consonant: 'ry', vowel: 'a' },
  'りゅ': { kana: 'りゅ', romaji: 'ryu', type: 'youon-y', constituentKana: ['り', 'ゅ'], script: ScriptType.Hiragana, consonant: 'ry', vowel: 'u' },
  'りょ': { kana: 'りょ', romaji: 'ryo', type: 'youon-y', constituentKana: ['り', 'ょ'], script: ScriptType.Hiragana, consonant: 'ry', vowel: 'o' },
  // G-line + y
  'ぎゃ': { kana: 'ぎゃ', romaji: 'gya', type: 'youon-y', baseKana: 'きゃ', constituentKana: ['ぎ', 'ゃ'], script: ScriptType.Hiragana, consonant: 'gy', vowel: 'a' },
  'ぎゅ': { kana: 'ぎゅ', romaji: 'gyu', type: 'youon-y', baseKana: 'きゅ', constituentKana: ['ぎ', 'ゅ'], script: ScriptType.Hiragana, consonant: 'gy', vowel: 'u' },
  'ぎょ': { kana: 'ぎょ', romaji: 'gyo', type: 'youon-y', baseKana: 'きょ', constituentKana: ['ぎ', 'ょ'], script: ScriptType.Hiragana, consonant: 'gy', vowel: 'o' },
  // J-line (from Sh) + y
  'じゃ': { kana: 'じゃ', romaji: 'ja', type: 'youon-y', baseKana: 'しゃ', constituentKana: ['じ', 'ゃ'], script: ScriptType.Hiragana, consonant: 'j', vowel: 'a' },
  'じゅ': { kana: 'じゅ', romaji: 'ju', type: 'youon-y', baseKana: 'しゅ', constituentKana: ['じ', 'ゅ'], script: ScriptType.Hiragana, consonant: 'j', vowel: 'u' },
  'じょ': { kana: 'じょ', romaji: 'jo', type: 'youon-y', baseKana: 'しょ', constituentKana: ['じ', 'ょ'], script: ScriptType.Hiragana, consonant: 'j', vowel: 'o' },
  // J-line (from Ch) + y (rarely distinguished in modern Japanese sound, ぢゃ vs じゃ)
  'ぢゃ': { kana: 'ぢゃ', romaji: 'ja', type: 'youon-y', baseKana: 'ちゃ', constituentKana: ['ぢ', 'ゃ'], script: ScriptType.Hiragana, consonant: 'j', vowel: 'a' },
  'ぢゅ': { kana: 'ぢゅ', romaji: 'ju', type: 'youon-y', baseKana: 'ちゅ', constituentKana: ['ぢ', 'ゅ'], script: ScriptType.Hiragana, consonant: 'j', vowel: 'u' },
  'ぢょ': { kana: 'ぢょ', romaji: 'jo', type: 'youon-y', baseKana: 'ちょ', constituentKana: ['ぢ', 'ょ'], script: ScriptType.Hiragana, consonant: 'j', vowel: 'o' },
  // B-line + y
  'びゃ': { kana: 'びゃ', romaji: 'bya', type: 'youon-y', baseKana: 'ひゃ', constituentKana: ['び', 'ゃ'], script: ScriptType.Hiragana, consonant: 'by', vowel: 'a' },
  'びゅ': { kana: 'びゅ', romaji: 'byu', type: 'youon-y', baseKana: 'ひゅ', constituentKana: ['び', 'ゅ'], script: ScriptType.Hiragana, consonant: 'by', vowel: 'u' },
  'びょ': { kana: 'びょ', romaji: 'byo', type: 'youon-y', baseKana: 'ひょ', constituentKana: ['び', 'ょ'], script: ScriptType.Hiragana, consonant: 'by', vowel: 'o' },
  // P-line + y
  'ぴゃ': { kana: 'ぴゃ', romaji: 'pya', type: 'youon-y', baseKana: 'ひゃ', constituentKana: ['ぴ', 'ゃ'], script: ScriptType.Hiragana, consonant: 'py', vowel: 'a' },
  'ぴゅ': { kana: 'ぴゅ', romaji: 'pyu', type: 'youon-y', baseKana: 'ひゅ', constituentKana: ['ぴ', 'ゅ'], script: ScriptType.Hiragana, consonant: 'py', vowel: 'u' },
  'ぴょ': { kana: 'ぴょ', romaji: 'pyo', type: 'youon-y', baseKana: 'ひょ', constituentKana: ['ぴ', 'ょ'], script: ScriptType.Hiragana, consonant: 'py', vowel: 'o' },

  // Hiragana Sokuon (Geminate Consonant)
  'っ': { kana: 'っ', romaji: '', type: 'sokuon', script: ScriptType.Hiragana }, // Romaji is context-dependent

  // Katakana Basic
  'ア': { kana: 'ア', romaji: 'a', type: 'basic', script: ScriptType.Katakana, consonant: '', vowel: 'a' },
  'イ': { kana: 'イ', romaji: 'i', type: 'basic', script: ScriptType.Katakana, consonant: '', vowel: 'i' },
  'ウ': { kana: 'ウ', romaji: 'u', type: 'basic', script: ScriptType.Katakana, consonant: '', vowel: 'u' },
  'エ': { kana: 'エ', romaji: 'e', type: 'basic', script: ScriptType.Katakana, consonant: '', vowel: 'e' },
  'オ': { kana: 'オ', romaji: 'o', type: 'basic', script: ScriptType.Katakana, consonant: '', vowel: 'o' },
  'カ': { kana: 'カ', romaji: 'ka', type: 'basic', script: ScriptType.Katakana, consonant: 'k', vowel: 'a' },
  'キ': { kana: 'キ', romaji: 'ki', type: 'basic', script: ScriptType.Katakana, consonant: 'k', vowel: 'i' },
  'ク': { kana: 'ク', romaji: 'ku', type: 'basic', script: ScriptType.Katakana, consonant: 'k', vowel: 'u' },
  'ケ': { kana: 'ケ', romaji: 'ke', type: 'basic', script: ScriptType.Katakana, consonant: 'k', vowel: 'e' },
  'コ': { kana: 'コ', romaji: 'ko', type: 'basic', script: ScriptType.Katakana, consonant: 'k', vowel: 'o' },
  'サ': { kana: 'サ', romaji: 'sa', type: 'basic', script: ScriptType.Katakana, consonant: 's', vowel: 'a' },
  'シ': { kana: 'シ', romaji: 'shi', type: 'basic', script: ScriptType.Katakana, consonant: 'sh', vowel: 'i' },
  'ス': { kana: 'ス', romaji: 'su', type: 'basic', script: ScriptType.Katakana, consonant: 's', vowel: 'u' },
  'セ': { kana: 'セ', romaji: 'se', type: 'basic', script: ScriptType.Katakana, consonant: 's', vowel: 'e' },
  'ソ': { kana: 'ソ', romaji: 'so', type: 'basic', script: ScriptType.Katakana, consonant: 's', vowel: 'o' },
  'タ': { kana: 'タ', romaji: 'ta', type: 'basic', script: ScriptType.Katakana, consonant: 't', vowel: 'a' },
  'チ': { kana: 'チ', romaji: 'chi', type: 'basic', script: ScriptType.Katakana, consonant: 'ch', vowel: 'i' },
  'ツ': { kana: 'ツ', romaji: 'tsu', type: 'basic', script: ScriptType.Katakana, consonant: 'ts', vowel: 'u' },
  'テ': { kana: 'テ', romaji: 'te', type: 'basic', script: ScriptType.Katakana, consonant: 't', vowel: 'e' },
  'ト': { kana: 'ト', romaji: 'to', type: 'basic', script: ScriptType.Katakana, consonant: 't', vowel: 'o' },
  'ナ': { kana: 'ナ', romaji: 'na', type: 'basic', script: ScriptType.Katakana, consonant: 'n', vowel: 'a' },
  'ニ': { kana: 'ニ', romaji: 'ni', type: 'basic', script: ScriptType.Katakana, consonant: 'n', vowel: 'i' },
  'ヌ': { kana: 'ヌ', romaji: 'nu', type: 'basic', script: ScriptType.Katakana, consonant: 'n', vowel: 'u' },
  'ネ': { kana: 'ネ', romaji: 'ne', type: 'basic', script: ScriptType.Katakana, consonant: 'n', vowel: 'e' },
  'ノ': { kana: 'ノ', romaji: 'no', type: 'basic', script: ScriptType.Katakana, consonant: 'n', vowel: 'o' },
  'ハ': { kana: 'ハ', romaji: 'ha', type: 'basic', script: ScriptType.Katakana, consonant: 'h', vowel: 'a' },
  'ヒ': { kana: 'ヒ', romaji: 'hi', type: 'basic', script: ScriptType.Katakana, consonant: 'h', vowel: 'i' },
  'フ': { kana: 'フ', romaji: 'fu', type: 'basic', script: ScriptType.Katakana, consonant: 'f', vowel: 'u' },
  'ヘ': { kana: 'ヘ', romaji: 'he', type: 'basic', script: ScriptType.Katakana, consonant: 'h', vowel: 'e' },
  'ホ': { kana: 'ホ', romaji: 'ho', type: 'basic', script: ScriptType.Katakana, consonant: 'h', vowel: 'o' },
  'マ': { kana: 'マ', romaji: 'ma', type: 'basic', script: ScriptType.Katakana, consonant: 'm', vowel: 'a' },
  'ミ': { kana: 'ミ', romaji: 'mi', type: 'basic', script: ScriptType.Katakana, consonant: 'm', vowel: 'i' },
  'ム': { kana: 'ム', romaji: 'mu', type: 'basic', script: ScriptType.Katakana, consonant: 'm', vowel: 'u' },
  'メ': { kana: 'メ', romaji: 'me', type: 'basic', script: ScriptType.Katakana, consonant: 'm', vowel: 'e' },
  'モ': { kana: 'モ', romaji: 'mo', type: 'basic', script: ScriptType.Katakana, consonant: 'm', vowel: 'o' },
  'ヤ': { kana: 'ヤ', romaji: 'ya', type: 'basic', script: ScriptType.Katakana, consonant: 'y', vowel: 'a' },
  'ユ': { kana: 'ユ', romaji: 'yu', type: 'basic', script: ScriptType.Katakana, consonant: 'y', vowel: 'u' },
  'ヨ': { kana: 'ヨ', romaji: 'yo', type: 'basic', script: ScriptType.Katakana, consonant: 'y', vowel: 'o' },
  'ラ': { kana: 'ラ', romaji: 'ra', type: 'basic', script: ScriptType.Katakana, consonant: 'r', vowel: 'a' },
  'リ': { kana: 'リ', romaji: 'ri', type: 'basic', script: ScriptType.Katakana, consonant: 'r', vowel: 'i' },
  'ル': { kana: 'ル', romaji: 'ru', type: 'basic', script: ScriptType.Katakana, consonant: 'r', vowel: 'u' },
  'レ': { kana: 'レ', romaji: 're', type: 'basic', script: ScriptType.Katakana, consonant: 'r', vowel: 'e' },
  'ロ': { kana: 'ロ', romaji: 'ro', type: 'basic', script: ScriptType.Katakana, consonant: 'r', vowel: 'o' },
  'ワ': { kana: 'ワ', romaji: 'wa', type: 'basic', script: ScriptType.Katakana, consonant: 'w', vowel: 'a' },
  'ヲ': { kana: 'ヲ', romaji: 'o', type: 'basic', script: ScriptType.Katakana, consonant: 'w', vowel: 'o' }, // Pronounced 'o'
  'ン': { kana: 'ン', romaji: 'n', type: 'n_syllabic', script: ScriptType.Katakana, consonant: 'n', vowel: '' },

  // Katakana Dakuten
  'ガ': { kana: 'ガ', romaji: 'ga', type: 'basic-d', baseKana: 'カ', script: ScriptType.Katakana, consonant: 'g', vowel: 'a' },
  'ギ': { kana: 'ギ', romaji: 'gi', type: 'basic-d', baseKana: 'キ', script: ScriptType.Katakana, consonant: 'g', vowel: 'i' },
  'グ': { kana: 'グ', romaji: 'gu', type: 'basic-d', baseKana: 'ク', script: ScriptType.Katakana, consonant: 'g', vowel: 'u' },
  'ゲ': { kana: 'ゲ', romaji: 'ge', type: 'basic-d', baseKana: 'ケ', script: ScriptType.Katakana, consonant: 'g', vowel: 'e' },
  'ゴ': { kana: 'ゴ', romaji: 'go', type: 'basic-d', baseKana: 'コ', script: ScriptType.Katakana, consonant: 'g', vowel: 'o' },
  'ザ': { kana: 'ザ', romaji: 'za', type: 'basic-d', baseKana: 'サ', script: ScriptType.Katakana, consonant: 'z', vowel: 'a' },
  'ジ': { kana: 'ジ', romaji: 'ji', type: 'basic-d', baseKana: 'シ', script: ScriptType.Katakana, consonant: 'j', vowel: 'i' },
  'ズ': { kana: 'ズ', romaji: 'zu', type: 'basic-d', baseKana: 'ス', script: ScriptType.Katakana, consonant: 'z', vowel: 'u' },
  'ゼ': { kana: 'ゼ', romaji: 'ze', type: 'basic-d', baseKana: 'セ', script: ScriptType.Katakana, consonant: 'z', vowel: 'e' },
  'ゾ': { kana: 'ゾ', romaji: 'zo', type: 'basic-d', baseKana: 'ソ', script: ScriptType.Katakana, consonant: 'z', vowel: 'o' },
  'ダ': { kana: 'ダ', romaji: 'da', type: 'basic-d', baseKana: 'タ', script: ScriptType.Katakana, consonant: 'd', vowel: 'a' },
  'ヂ': { kana: 'ヂ', romaji: 'ji', type: 'basic-d', baseKana: 'チ', script: ScriptType.Katakana, consonant: 'j', vowel: 'i' },
  'ヅ': { kana: 'ヅ', romaji: 'zu', type: 'basic-d', baseKana: 'ツ', script: ScriptType.Katakana, consonant: 'z', vowel: 'u' },
  'デ': { kana: 'デ', romaji: 'de', type: 'basic-d', baseKana: 'テ', script: ScriptType.Katakana, consonant: 'd', vowel: 'e' },
  'ド': { kana: 'ド', romaji: 'do', type: 'basic-d', baseKana: 'ト', script: ScriptType.Katakana, consonant: 'd', vowel: 'o' },
  'バ': { kana: 'バ', romaji: 'ba', type: 'basic-d', baseKana: 'ハ', script: ScriptType.Katakana, consonant: 'b', vowel: 'a' },
  'ビ': { kana: 'ビ', romaji: 'bi', type: 'basic-d', baseKana: 'ヒ', script: ScriptType.Katakana, consonant: 'b', vowel: 'i' },
  'ブ': { kana: 'ブ', romaji: 'bu', type: 'basic-d', baseKana: 'フ', script: ScriptType.Katakana, consonant: 'b', vowel: 'u' },
  'ベ': { kana: 'ベ', romaji: 'be', type: 'basic-d', baseKana: 'ヘ', script: ScriptType.Katakana, consonant: 'b', vowel: 'e' },
  'ボ': { kana: 'ボ', romaji: 'bo', type: 'basic-d', baseKana: 'ホ', script: ScriptType.Katakana, consonant: 'b', vowel: 'o' },

  // Katakana Handakuten
  'パ': { kana: 'パ', romaji: 'pa', type: 'basic-hp', baseKana: 'ハ', script: ScriptType.Katakana, consonant: 'p', vowel: 'a' },
  'ピ': { kana: 'ピ', romaji: 'pi', type: 'basic-hp', baseKana: 'ヒ', script: ScriptType.Katakana, consonant: 'p', vowel: 'i' },
  'プ': { kana: 'プ', romaji: 'pu', type: 'basic-hp', baseKana: 'フ', script: ScriptType.Katakana, consonant: 'p', vowel: 'u' },
  'ペ': { kana: 'ペ', romaji: 'pe', type: 'basic-hp', baseKana: 'ヘ', script: ScriptType.Katakana, consonant: 'p', vowel: 'e' },
  'ポ': { kana: 'ポ', romaji: 'po', type: 'basic-hp', baseKana: 'ホ', script: ScriptType.Katakana, consonant: 'p', vowel: 'o' },

  // Katakana Small Yōon Vowels
  'ャ': { kana: 'ャ', romaji: 'ya', type: 'youon-y', script: ScriptType.Katakana, vowel: 'a' },
  'ュ': { kana: 'ュ', romaji: 'yu', type: 'youon-y', script: ScriptType.Katakana, vowel: 'u' },
  'ョ': { kana: 'ョ', romaji: 'yo', type: 'youon-y', script: ScriptType.Katakana, vowel: 'o' },
  'ァ': { kana: 'ァ', romaji: 'a', type: 'extended', script: ScriptType.Katakana, vowel: 'a' }, // Small a, i, u, e, o for extended sounds
  'ィ': { kana: 'ィ', romaji: 'i', type: 'extended', script: ScriptType.Katakana, vowel: 'i' },
  'ゥ': { kana: 'ゥ', romaji: 'u', type: 'extended', script: ScriptType.Katakana, vowel: 'u' },
  'ェ': { kana: 'ェ', romaji: 'e', type: 'extended', script: ScriptType.Katakana, vowel: 'e' },
  'ォ': { kana: 'ォ', romaji: 'o', type: 'extended', script: ScriptType.Katakana, vowel: 'o' },
  'ヮ': { kana: 'ヮ', romaji: 'wa', type: 'youon-w', script: ScriptType.Katakana, vowel: 'a' }, // Less common

  // Katakana Yōon (Contracted sounds) - K-line + y
  'キャ': { kana: 'キャ', romaji: 'kya', type: 'youon-y', constituentKana: ['キ', 'ャ'], script: ScriptType.Katakana, consonant: 'ky', vowel: 'a' },
  'キュ': { kana: 'キュ', romaji: 'kyu', type: 'youon-y', constituentKana: ['キ', 'ュ'], script: ScriptType.Katakana, consonant: 'ky', vowel: 'u' },
  'キョ': { kana: 'キョ', romaji: 'kyo', type: 'youon-y', constituentKana: ['キ', 'ョ'], script: ScriptType.Katakana, consonant: 'ky', vowel: 'o' },
  'シャ': { kana: 'シャ', romaji: 'sha', type: 'youon-y', constituentKana: ['シ', 'ャ'], script: ScriptType.Katakana, consonant: 'sh', vowel: 'a' },
  'シュ': { kana: 'シュ', romaji: 'shu', type: 'youon-y', constituentKana: ['シ', 'ュ'], script: ScriptType.Katakana, consonant: 'sh', vowel: 'u' },
  'ショ': { kana: 'ショ', romaji: 'sho', type: 'youon-y', constituentKana: ['シ', 'ョ'], script: ScriptType.Katakana, consonant: 'sh', vowel: 'o' },
  'チャ': { kana: 'チャ', romaji: 'cha', type: 'youon-y', constituentKana: ['チ', 'ャ'], script: ScriptType.Katakana, consonant: 'ch', vowel: 'a' },
  'チュ': { kana: 'チュ', romaji: 'chu', type: 'youon-y', constituentKana: ['チ', 'ュ'], script: ScriptType.Katakana, consonant: 'ch', vowel: 'u' },
  'チョ': { kana: 'チョ', romaji: 'cho', type: 'youon-y', constituentKana: ['チ', 'ョ'], script: ScriptType.Katakana, consonant: 'ch', vowel: 'o' },
  'ニャ': { kana: 'ニャ', romaji: 'nya', type: 'youon-y', constituentKana: ['ニ', 'ャ'], script: ScriptType.Katakana, consonant: 'ny', vowel: 'a' },
  'ニュ': { kana: 'ニュ', romaji: 'nyu', type: 'youon-y', constituentKana: ['ニ', 'ュ'], script: ScriptType.Katakana, consonant: 'ny', vowel: 'u' },
  'ニョ': { kana: 'ニョ', romaji: 'nyo', type: 'youon-y', constituentKana: ['ニ', 'ョ'], script: ScriptType.Katakana, consonant: 'ny', vowel: 'o' },
  'ヒャ': { kana: 'ヒャ', romaji: 'hya', type: 'youon-y', constituentKana: ['ヒ', 'ャ'], script: ScriptType.Katakana, consonant: 'hy', vowel: 'a' },
  'ヒュ': { kana: 'ヒュ', romaji: 'hyu', type: 'youon-y', constituentKana: ['ヒ', 'ュ'], script: ScriptType.Katakana, consonant: 'hy', vowel: 'u' },
  'ヒョ': { kana: 'ヒョ', romaji: 'hyo', type: 'youon-y', constituentKana: ['ヒ', 'ョ'], script: ScriptType.Katakana, consonant: 'hy', vowel: 'o' },
  'ミャ': { kana: 'ミャ', romaji: 'mya', type: 'youon-y', constituentKana: ['ミ', 'ャ'], script: ScriptType.Katakana, consonant: 'my', vowel: 'a' },
  'ミュ': { kana: 'ミュ', romaji: 'myu', type: 'youon-y', constituentKana: ['ミ', 'ュ'], script: ScriptType.Katakana, consonant: 'my', vowel: 'u' },
  'ミョ': { kana: 'ミョ', romaji: 'myo', type: 'youon-y', constituentKana: ['ミ', 'ョ'], script: ScriptType.Katakana, consonant: 'my', vowel: 'o' },
  'リャ': { kana: 'リャ', romaji: 'rya', type: 'youon-y', constituentKana: ['リ', 'ャ'], script: ScriptType.Katakana, consonant: 'ry', vowel: 'a' },
  'リュ': { kana: 'リュ', romaji: 'ryu', type: 'youon-y', constituentKana: ['リ', 'ュ'], script: ScriptType.Katakana, consonant: 'ry', vowel: 'u' },
  'リョ': { kana: 'リョ', romaji: 'ryo', type: 'youon-y', constituentKana: ['リ', 'ョ'], script: ScriptType.Katakana, consonant: 'ry', vowel: 'o' },
  'ギャ': { kana: 'ギャ', romaji: 'gya', type: 'youon-y', baseKana: 'キャ', constituentKana: ['ギ', 'ャ'], script: ScriptType.Katakana, consonant: 'gy', vowel: 'a' },
  'ギュ': { kana: 'ギュ', romaji: 'gyu', type: 'youon-y', baseKana: 'キュ', constituentKana: ['ギ', 'ュ'], script: ScriptType.Katakana, consonant: 'gy', vowel: 'u' },
  'ギョ': { kana: 'ギョ', romaji: 'gyo', type: 'youon-y', baseKana: 'キョ', constituentKana: ['ギ', 'ョ'], script: ScriptType.Katakana, consonant: 'gy', vowel: 'o' },
  'ジャ': { kana: 'ジャ', romaji: 'ja', type: 'youon-y', baseKana: 'シャ', constituentKana: ['ジ', 'ャ'], script: ScriptType.Katakana, consonant: 'j', vowel: 'a' },
  'ジュ': { kana: 'ジュ', romaji: 'ju', type: 'youon-y', baseKana: 'シュ', constituentKana: ['ジ', 'ュ'], script: ScriptType.Katakana, consonant: 'j', vowel: 'u' },
  'ジョ': { kana: 'ジョ', romaji: 'jo', type: 'youon-y', baseKana: 'ショ', constituentKana: ['ジ', 'ョ'], script: ScriptType.Katakana, consonant: 'j', vowel: 'o' },
  'ヂャ': { kana: 'ヂャ', romaji: 'ja', type: 'youon-y', baseKana: 'チャ', constituentKana: ['ヂ', 'ャ'], script: ScriptType.Katakana, consonant: 'j', vowel: 'a' },
  'ヂュ': { kana: 'ヂュ', romaji: 'ju', type: 'youon-y', baseKana: 'チュ', constituentKana: ['ヂ', 'ュ'], script: ScriptType.Katakana, consonant: 'j', vowel: 'u' },
  'ヂョ': { kana: 'ヂョ', romaji: 'jo', type: 'youon-y', baseKana: 'チョ', constituentKana: ['ヂ', 'ョ'], script: ScriptType.Katakana, consonant: 'j', vowel: 'o' },
  'ビャ': { kana: 'ビャ', romaji: 'bya', type: 'youon-y', baseKana: 'ヒャ', constituentKana: ['ビ', 'ャ'], script: ScriptType.Katakana, consonant: 'by', vowel: 'a' },
  'ビュ': { kana: 'ビュ', romaji: 'byu', type: 'youon-y', baseKana: 'ヒュ', constituentKana: ['ビ', 'ュ'], script: ScriptType.Katakana, consonant: 'by', vowel: 'u' },
  'ビョ': { kana: 'ビョ', romaji: 'byo', type: 'youon-y', baseKana: 'ヒョ', constituentKana: ['ビ', 'ょ'], script: ScriptType.Katakana, consonant: 'by', vowel: 'o' },
  'ピャ': { kana: 'ピャ', romaji: 'pya', type: 'youon-y', baseKana: 'ヒャ', constituentKana: ['ピ', 'ャ'], script: ScriptType.Katakana, consonant: 'py', vowel: 'a' },
  'ピュ': { kana: 'ピュ', romaji: 'pyu', type: 'youon-y', baseKana: 'ヒュ', constituentKana: ['ピ', 'ュ'], script: ScriptType.Katakana, consonant: 'py', vowel: 'u' },
  'ピョ': { kana: 'ピョ', romaji: 'pyo', type: 'youon-y', baseKana: 'ヒョ', constituentKana: ['ピ', 'ョ'], script: ScriptType.Katakana, consonant: 'py', vowel: 'o' },

  // Katakana Extended sounds (for foreign words)
  'ヴァ': { kana: 'ヴァ', romaji: 'va', type: 'extended', constituentKana: ['ヴ', 'ァ'], script: ScriptType.Katakana, consonant: 'v', vowel: 'a' },
  'ヴィ': { kana: 'ヴィ', romaji: 'vi', type: 'extended', constituentKana: ['ヴ', 'ィ'], script: ScriptType.Katakana, consonant: 'v', vowel: 'i' },
  'ヴ':   { kana: 'ヴ', romaji: 'vu', type: 'extended', baseKana: 'ウ', script: ScriptType.Katakana, consonant: 'v', vowel: 'u' }, // Often just ヴ for "vu"
  'ヴェ': { kana: 'ヴェ', romaji: 've', type: 'extended', constituentKana: ['ヴ', 'ェ'], script: ScriptType.Katakana, consonant: 'v', vowel: 'e' },
  'ヴォ': { kana: 'ヴォ', romaji: 'vo', type: 'extended', constituentKana: ['ヴ', 'ォ'], script: ScriptType.Katakana, consonant: 'v', vowel: 'o' },
  'ファ': { kana: 'ファ', romaji: 'fa', type: 'extended', constituentKana: ['フ', 'ァ'], script: ScriptType.Katakana, consonant: 'f', vowel: 'a' },
  'フィ': { kana: 'フィ', romaji: 'fi', type: 'extended', constituentKana: ['フ', 'ィ'], script: ScriptType.Katakana, consonant: 'f', vowel: 'i' },
  'フェ': { kana: 'フェ', romaji: 'fe', type: 'extended', constituentKana: ['フ', 'ェ'], script: ScriptType.Katakana, consonant: 'f', vowel: 'e' },
  'フォ': { kana: 'フォ', romaji: 'fo', type: 'extended', constituentKana: ['フ', 'ォ'], script: ScriptType.Katakana, consonant: 'f', vowel: 'o' },
  'ティ': { kana: 'ティ', romaji: 'ti', type: 'extended', constituentKana: ['テ', 'ィ'], script: ScriptType.Katakana, consonant: 't', vowel: 'i' },
  'トゥ': { kana: 'トゥ', romaji: 'tu', type: 'extended', constituentKana: ['ト', 'ゥ'], script: ScriptType.Katakana, consonant: 't', vowel: 'u' },
  'テュ': { kana: 'テュ', romaji: 'tyu', type: 'extended', constituentKana: ['テ', 'ュ'], script: ScriptType.Katakana, consonant: 'ty', vowel: 'u' },
  'ディ': { kana: 'ディ', romaji: 'di', type: 'extended', constituentKana: ['デ', 'ィ'], script: ScriptType.Katakana, consonant: 'd', vowel: 'i' },
  'ドゥ': { kana: 'ドゥ', romaji: 'du', type: 'extended', constituentKana: ['ド', 'ゥ'], script: ScriptType.Katakana, consonant: 'd', vowel: 'u' },
  'デュ': { kana: 'デュ', romaji: 'dyu', type: 'extended', constituentKana: ['デ', 'ュ'], script: ScriptType.Katakana, consonant: 'dy', vowel: 'u' },
  'チェ': { kana: 'チェ', romaji: 'che', type: 'extended', constituentKana: ['チ', 'ェ'], script: ScriptType.Katakana, consonant: 'ch', vowel: 'e'}, // e.g. Check
  'シェ': { kana: 'シェ', romaji: 'she', type: 'extended', constituentKana: ['シ', 'ェ'], script: ScriptType.Katakana, consonant: 'sh', vowel: 'e'}, // e.g. Share
  'ジェ': { kana: 'ジェ', romaji: 'je', type: 'extended', constituentKana: ['ジ', 'ェ'], script: ScriptType.Katakana, consonant: 'j', vowel: 'e'}, // e.g. Jet

  // Katakana Chōonpu (Long Vowel Mark)
  'ー': { kana: 'ー', romaji: '', type: 'choonpu', script: ScriptType.Katakana },
  // Katakana Sokuon
  'ッ': { kana: 'ッ', romaji: '', type: 'sokuon', script: ScriptType.Katakana },
};

export const KANA_LINES: { [key in ScriptType]: { [lineId: string]: KanaLine } } = {
  [ScriptType.Hiragana]: {
    'a-line': { id: 'a-line', name: 'あ行 (a i u e o)', kana: [MORA_DATA['あ'], MORA_DATA['い'], MORA_DATA['う'], MORA_DATA['え'], MORA_DATA['お']] },
    'ka-line': { id: 'ka-line', name: 'か行 (ka ki ku ke ko)', kana: [MORA_DATA['か'], MORA_DATA['き'], MORA_DATA['く'], MORA_DATA['け'], MORA_DATA['こ']] },
    'sa-line': { id: 'sa-line', name: 'さ行 (sa shi su se so)', kana: [MORA_DATA['さ'], MORA_DATA['し'], MORA_DATA['す'], MORA_DATA['せ'], MORA_DATA['そ']] },
    'ta-line': { id: 'ta-line', name: 'た行 (ta chi tsu te to)', kana: [MORA_DATA['た'], MORA_DATA['ち'], MORA_DATA['つ'], MORA_DATA['て'], MORA_DATA['と']] },
    'na-line': { id: 'na-line', name: 'な行 (na ni nu ne no)', kana: [MORA_DATA['な'], MORA_DATA['に'], MORA_DATA['ぬ'], MORA_DATA['ね'], MORA_DATA['の']] },
    'ha-line': { id: 'ha-line', name: 'は行 (ha hi fu he ho)', kana: [MORA_DATA['は'], MORA_DATA['ひ'], MORA_DATA['ふ'], MORA_DATA['へ'], MORA_DATA['ほ']] },
    'ma-line': { id: 'ma-line', name: 'ま行 (ma mi mu me mo)', kana: [MORA_DATA['ま'], MORA_DATA['み'], MORA_DATA['む'], MORA_DATA['め'], MORA_DATA['も']] },
    'ya-line': { id: 'ya-line', name: 'や行 (ya yu yo)', kana: [MORA_DATA['や'], MORA_DATA['ゆ'], MORA_DATA['よ']] },
    'ra-line': { id: 'ra-line', name: 'ら行 (ra ri ru re ro)', kana: [MORA_DATA['ら'], MORA_DATA['り'], MORA_DATA['る'], MORA_DATA['れ'], MORA_DATA['ろ']] },
    'wa-line': { id: 'wa-line', name: 'わ行 (wa wo n)', kana: [MORA_DATA['わ'], MORA_DATA['を'], MORA_DATA['ん']] },
    'ga-line': { id: 'ga-line', name: 'が行 (ga gi gu ge go)', kana: [MORA_DATA['が'], MORA_DATA['ぎ'], MORA_DATA['ぐ'], MORA_DATA['げ'], MORA_DATA['ご']] },
    'za-line': { id: 'za-line', name: 'ざ行 (za ji zu ze zo)', kana: [MORA_DATA['ざ'], MORA_DATA['じ'], MORA_DATA['ず'], MORA_DATA['ぜ'], MORA_DATA['ぞ']] },
    'da-line': { id: 'da-line', name: 'だ行 (da ji zu de do)', kana: [MORA_DATA['だ'], MORA_DATA['ぢ'], MORA_DATA['づ'], MORA_DATA['で'], MORA_DATA['ど']] },
    'ba-line': { id: 'ba-line', name: 'ば行 (ba bi bu be bo)', kana: [MORA_DATA['ば'], MORA_DATA['び'], MORA_DATA['ぶ'], MORA_DATA['べ'], MORA_DATA['ぼ']] },
    'pa-line': { id: 'pa-line', name: 'ぱ行 (pa pi pu pe po)', kana: [MORA_DATA['ぱ'], MORA_DATA['ぴ'], MORA_DATA['ぷ'], MORA_DATA['ぺ'], MORA_DATA['ぽ']] },
    'kya-line': { id: 'kya-line', name: 'きゃ行 (kya kyu kyo)', kana: [MORA_DATA['きゃ'], MORA_DATA['きゅ'], MORA_DATA['きょ']]},
    'sha-line': { id: 'sha-line', name: 'しゃ行 (sha shu sho)', kana: [MORA_DATA['しゃ'], MORA_DATA['しゅ'], MORA_DATA['しょ']]},
    'cha-line': { id: 'cha-line', name: 'ちゃ行 (cha chu cho)', kana: [MORA_DATA['ちゃ'], MORA_DATA['ちゅ'], MORA_DATA['ちょ']]},
    'nya-line': { id: 'nya-line', name: 'にゃ行 (nya nyu nyo)', kana: [MORA_DATA['にゃ'], MORA_DATA['にゅ'], MORA_DATA['にょ']]},
    'hya-line': { id: 'hya-line', name: 'ひゃ行 (hya hyu hyo)', kana: [MORA_DATA['ひゃ'], MORA_DATA['ひゅ'], MORA_DATA['ひょ']]},
    'mya-line': { id: 'mya-line', name: 'みゃ行 (mya myu myo)', kana: [MORA_DATA['みゃ'], MORA_DATA['みゅ'], MORA_DATA['みょ']]},
    'rya-line': { id: 'rya-line', name: 'りゃ行 (rya ryu ryo)', kana: [MORA_DATA['りゃ'], MORA_DATA['りゅ'], MORA_DATA['りょ']]},
    'gya-line': { id: 'gya-line', name: 'ぎゃ行 (gya gyu gyo)', kana: [MORA_DATA['ぎゃ'], MORA_DATA['ぎゅ'], MORA_DATA['ぎょ']]},
    'ja-line': { id: 'ja-line', name: 'じゃ行 (ja ju jo)', kana: [MORA_DATA['じゃ'], MORA_DATA['じゅ'], MORA_DATA['じょ']]}, // From Shi+Dakuten
    'dja-line': { id: 'dja-line', name: 'ぢゃ行 (ja ju jo)', kana: [MORA_DATA['ぢゃ'], MORA_DATA['ぢゅ'], MORA_DATA['ぢょ']]},// From Chi+Dakuten
    'bya-line': { id: 'bya-line', name: 'びゃ行 (bya byu byo)', kana: [MORA_DATA['びゃ'], MORA_DATA['びゅ'], MORA_DATA['びょ']]},
    'pya-line': { id: 'pya-line', name: 'ぴゃ行 (pya pyu pyo)', kana: [MORA_DATA['ぴゃ'], MORA_DATA['ぴゅ'], MORA_DATA['ぴょ']]},
    'sokuon-line': {id: 'sokuon-line', name: '促音 (っ)', kana: [MORA_DATA['っ']]},
  },
  [ScriptType.Katakana]: {
    'a-line': { id: 'a-line', name: 'ア行 (A I U E O)', kana: [MORA_DATA['ア'], MORA_DATA['イ'], MORA_DATA['ウ'], MORA_DATA['エ'], MORA_DATA['オ']] },
    'ka-line': { id: 'ka-line', name: 'カ行 (KA KI KU KE KO)', kana: [MORA_DATA['カ'], MORA_DATA['キ'], MORA_DATA['ク'], MORA_DATA['ケ'], MORA_DATA['コ']] },
    'sa-line': { id: 'sa-line', name: 'サ行 (SA SHI SU SE SO)', kana: [MORA_DATA['サ'], MORA_DATA['シ'], MORA_DATA['ス'], MORA_DATA['セ'], MORA_DATA['ソ']] },
    'ta-line': { id: 'ta-line', name: 'タ行 (TA CHI TSU TE TO)', kana: [MORA_DATA['タ'], MORA_DATA['チ'], MORA_DATA['ツ'], MORA_DATA['テ'], MORA_DATA['ト']] },
    'na-line': { id: 'na-line', name: 'ナ行 (NA NI NU NE NO)', kana: [MORA_DATA['ナ'], MORA_DATA['ニ'], MORA_DATA['ヌ'], MORA_DATA['ネ'], MORA_DATA['ノ']] },
    'ha-line': { id: 'ha-line', name: 'ハ行 (HA HI FU HE HO)', kana: [MORA_DATA['ハ'], MORA_DATA['ヒ'], MORA_DATA['フ'], MORA_DATA['ヘ'], MORA_DATA['ホ']] },
    'ma-line': { id: 'ma-line', name: 'マ行 (MA MI MU ME MO)', kana: [MORA_DATA['マ'], MORA_DATA['ミ'], MORA_DATA['ム'], MORA_DATA['メ'], MORA_DATA['モ']] },
    'ya-line': { id: 'ya-line', name: 'ヤ行 (YA YU YO)', kana: [MORA_DATA['ヤ'], MORA_DATA['ユ'], MORA_DATA['ヨ']] },
    'ra-line': { id: 'ra-line', name: 'ラ行 (RA RI RU RE RO)', kana: [MORA_DATA['ラ'], MORA_DATA['リ'], MORA_DATA['ル'], MORA_DATA['レ'], MORA_DATA['ロ']] },
    'wa-line': { id: 'wa-line', name: 'ワ行 (WA WO N)', kana: [MORA_DATA['ワ'], MORA_DATA['ヲ'], MORA_DATA['ン']] },
    'ga-line': { id: 'ga-line', name: 'ガ行 (GA GI GU GE GO)', kana: [MORA_DATA['ガ'], MORA_DATA['ギ'], MORA_DATA['グ'], MORA_DATA['ゲ'], MORA_DATA['ゴ']] },
    'za-line': { id: 'za-line', name: 'ザ行 (ZA JI ZU ZE ZO)', kana: [MORA_DATA['ザ'], MORA_DATA['ジ'], MORA_DATA['ズ'], MORA_DATA['ゼ'], MORA_DATA['ゾ']] },
    'da-line': { id: 'da-line', name: 'ダ行 (DA DJI DZU DE DO)', kana: [MORA_DATA['ダ'], MORA_DATA['ヂ'], MORA_DATA['ヅ'], MORA_DATA['デ'], MORA_DATA['ド']] },
    'ba-line': { id: 'ba-line', name: 'バ行 (BA BI BU BE BO)', kana: [MORA_DATA['バ'], MORA_DATA['ビ'], MORA_DATA['ブ'], MORA_DATA['ベ'], MORA_DATA['ボ']] },
    'pa-line': { id: 'pa-line', name: 'パ行 (PA PI PU PE PO)', kana: [MORA_DATA['パ'], MORA_DATA['ピ'], MORA_DATA['プ'], MORA_DATA['ペ'], MORA_DATA['ポ']] },
    'kya-line': { id: 'kya-line', name: 'キャ行 (KYA KYU KYO)', kana: [MORA_DATA['キャ'], MORA_DATA['キュ'], MORA_DATA['キョ']]},
    'sha-line': { id: 'sha-line', name: 'シャ行 (SHA SHU SHO)', kana: [MORA_DATA['シャ'], MORA_DATA['シュ'], MORA_DATA['ショ']]},
    // ... other Katakana yōon lines (assuming they are similar to Hiragana in MORA_DATA)
    'nya-line': { id: 'nya-line', name: 'ニャ行 (NYA NYU NYO)', kana: [MORA_DATA['ニャ'], MORA_DATA['ニュ'], MORA_DATA['ニョ']]},
    'hya-line': { id: 'hya-line', name: 'ヒャ行 (HYA HYU HYO)', kana: [MORA_DATA['ヒャ'], MORA_DATA['ヒュ'], MORA_DATA['ヒョ']]},
    'mya-line': { id: 'mya-line', name: 'ミャ行 (MYA MYU MYO)', kana: [MORA_DATA['ミャ'], MORA_DATA['ミュ'], MORA_DATA['ミョ']]},
    'rya-line': { id: 'rya-line', name: 'リャ行 (RYA RYU RYO)', kana: [MORA_DATA['リャ'], MORA_DATA['リュ'], MORA_DATA['リョ']]},
    'gya-line': { id: 'gya-line', name: 'ギャ行 (GYA GYU GYO)', kana: [MORA_DATA['ギャ'], MORA_DATA['ギュ'], MORA_DATA['ギョ']]},
    'ja-line': { id: 'ja-line', name: 'ジャ行 (JA JU JO)', kana: [MORA_DATA['ジャ'], MORA_DATA['ジュ'], MORA_DATA['ジョ']]},
    'bya-line': { id: 'bya-line', name: 'ビャ行 (BYA BYU BYO)', kana: [MORA_DATA['ビャ'], MORA_DATA['ビュ'], MORA_DATA['ビョ']]},
    'pya-line': { id: 'pya-line', name: 'ピャ行 (PYA PYU PYO)', kana: [MORA_DATA['ピャ'], MORA_DATA['ピュ'], MORA_DATA['ピョ']]},
    'va-line': { id: 'va-line', name: 'ヴァ行 (VA VI VU VE VO)', kana: [MORA_DATA['ヴァ'], MORA_DATA['ヴィ'], MORA_DATA['ヴ'], MORA_DATA['ヴェ'], MORA_DATA['ヴォ']]},
    'fa-line': { id: 'fa-line', name: 'ファ行 (FA FI FU FE FO)', kana: [MORA_DATA['ファ'], MORA_DATA['フィ'], MORA_DATA['フ'], MORA_DATA['フェ'], MORA_DATA['フォ']]},
    'ti-du-line': {id: 'ti-du-line', name: 'ティ/トゥ/ディ/ドゥ/テュ/デュ', kana: [MORA_DATA['ティ'], MORA_DATA['トゥ'], MORA_DATA['ディ'], MORA_DATA['ドゥ'], MORA_DATA['テュ'], MORA_DATA['デュ']]},
    'che-line': {id: 'che-line', name: 'チェ/シェ/ジェ', kana: [MORA_DATA['チェ'],MORA_DATA['シェ'],MORA_DATA['ジェ']]},
    'sokuon-choonpu-line': {id: 'sokuon-choonpu-line', name: '促音 (ッ) 長音 (ー)', kana: [MORA_DATA['ッ'], MORA_DATA['ー']]},
  },
};

export const KANA_LINE_ORDER: { [key in ScriptType]: string[] } = {
  [ScriptType.Hiragana]: [
    'a-line', 'ka-line', 'sa-line', 'ta-line', 'na-line', 
    'ha-line', 'ma-line', 'ya-line', 'ra-line', 'wa-line',
    'ga-line', 'za-line', 'da-line', 'ba-line', 'pa-line',
    'kya-line', 'sha-line', 'cha-line', 'nya-line', 'hya-line', 
    'mya-line', 'rya-line', 'gya-line', 'ja-line', 'dja-line', 
    'bya-line', 'pya-line', 'sokuon-line',
  ],
  [ScriptType.Katakana]: [
    'a-line', 'ka-line', 'sa-line', 'ta-line', 'na-line', 
    'ha-line', 'ma-line', 'ya-line', 'ra-line', 'wa-line',
    'ga-line', 'za-line', 'da-line', 'ba-line', 'pa-line',
    'kya-line', 'sha-line', 'nya-line', 'hya-line', 'mya-line', 'rya-line',
    'gya-line', 'ja-line', 'bya-line', 'pya-line',
    'va-line', 'fa-line', 'ti-du-line', 'che-line',
    'sokuon-choonpu-line',
  ],
};

export const MASTER_VOCAB: { [key in ScriptType]: Word[] } = {
  [ScriptType.Hiragana]: [
    // Basic
    { kana: 'あおい', romaji: 'aoi', length: 3, constituentKana: ['あ', 'お', 'い'], tags: ['color', 'adjective'] },
    { kana: 'いえ', romaji: 'ie', length: 2, constituentKana: ['い', 'え'], tags: ['place', 'noun'] },
    { kana: 'うえ', romaji: 'ue', length: 2, constituentKana: ['う', 'え'], tags: ['position', 'noun'] },
    { kana: 'えき', romaji: 'eki', length: 2, constituentKana: ['え', 'き'], tags: ['place', 'noun'] },
    { kana: 'おおきい', romaji: 'ōkii', length: 4, constituentKana: ['お', 'お', 'き', 'い'], tags: ['size', 'adjective'] },
    { kana: 'かさ', romaji: 'kasa', length: 2, constituentKana: ['か', 'さ'], tags: ['item', 'noun'] },
    { kana: 'くつ', romaji: 'kutsu', length: 2, constituentKana: ['く', 'つ'], tags: ['item', 'noun'] },
    { kana: 'すし', romaji: 'sushi', length: 2, constituentKana: ['す', 'し'], tags: ['food', 'noun'] },
    { kana: 'せかい', romaji: 'sekai', length: 3, constituentKana: ['せ', 'か', 'い'], tags: ['concept', 'noun'] },
    { kana: 'ちかてつ', romaji: 'chikatetsu', length: 4, constituentKana: ['ち', 'か', 'て', 'つ'], tags: ['transport', 'noun'] },
    { kana: 'つくえ', romaji: 'tsukue', length: 3, constituentKana: ['つ', 'く', 'え'], tags: ['item', 'noun'] },
    { kana: 'てがみ', romaji: 'tegami', length: 3, constituentKana: ['て', 'が', 'み'], phoneticProfile: { hasVoiced: true }, tags: ['item', 'noun'] },
    { kana: 'なか', romaji: 'naka', length: 2, constituentKana: ['な', 'か'], tags: ['position', 'noun'] },
    { kana: 'ねこ', romaji: 'neko', length: 2, constituentKana: ['ね', 'こ'], tags: ['animal', 'noun'] },
    { kana: 'いぬ', romaji: 'inu', length: 2, constituentKana: ['い', 'ぬ'], tags: ['animal', 'noun'] },
    { kana: 'はな', romaji: 'hana', length: 2, constituentKana: ['は', 'な'], tags: ['nature', 'noun'] }, // flower or nose
    { kana: 'ふね', romaji: 'fune', length: 2, constituentKana: ['ふ', 'ね'], tags: ['transport', 'noun'] },
    { kana: 'みせ', romaji: 'mise', length: 2, constituentKana: ['み', 'せ'], tags: ['place', 'noun'] },
    { kana: 'やま', romaji: 'yama', length: 2, constituentKana: ['や', 'ま'], tags: ['nature', 'noun'] },
    { kana: 'ゆめ', romaji: 'yume', length: 2, constituentKana: ['ゆ', 'め'], tags: ['concept', 'noun'] },
    { kana: 'よる', romaji: 'yoru', length: 2, constituentKana: ['よ', 'る'], tags: ['time', 'noun'] }, // night, corrected spacing
    { kana: 'くるま', romaji: 'kuruma', length: 3, constituentKana: ['く', 'る', 'ま'], tags:['transport', 'noun']},

    // Voiced/Handakuten
    { kana: 'でんわ', romaji: 'denwa', length: 3, constituentKana: ['で', 'ん', 'わ'], phoneticProfile: { hasVoiced: true }, tags: ['item', 'noun'] },
    { kana: 'かばん', romaji: 'kaban', length: 3, constituentKana: ['か', 'ば', 'ん'], phoneticProfile: { hasVoiced: true }, tags: ['item', 'noun'] },
    { kana: 'えんぴつ', romaji: 'enpitsu', length: 4, constituentKana: ['え', 'ん', 'ぴ', 'つ'], phoneticProfile: { hasHandakuten: true }, tags: ['item', 'noun'] },
    { kana: 'かぜ', romaji: 'kaze', length: 2, constituentKana: ['か', 'ぜ'], phoneticProfile: {hasVoiced: true}, tags: ['nature', 'noun'] }, // wind or cold (illness)
    { kana: 'ともだち', romaji: 'tomodachi', length: 4, constituentKana: ['と', 'も', 'だ', 'ち'], phoneticProfile: {hasVoiced: true}, tags: ['people', 'noun']},

    // Sokuon
    { kana: 'がっこう', romaji: 'gakkō', length: 4, constituentKana: ['が', 'っ', 'こ', 'う'], phoneticProfile: { hasVoiced: true, hasSokuon: true }, tags: ['place', 'noun'] },
    { kana: 'きっぷ', romaji: 'kippu', length: 3, constituentKana: ['き', 'っ', 'ぷ'], phoneticProfile: { hasSokuon: true, hasHandakuten: true }, tags: ['item', 'noun'] },
    { kana: 'ざっし', romaji: 'zasshi', length: 3, constituentKana: ['ざ', 'っ', 'し'], phoneticProfile: { hasVoiced: true, hasSokuon: true }, tags: ['item', 'noun'] },
    { kana: 'けっこん', romaji: 'kekkon', length: 3, constituentKana: ['け', 'っ', 'こ', 'ん'], phoneticProfile: { hasSokuon: true }, tags: ['event', 'noun'] },

    // Yōon
    { kana: 'きょう', romaji: 'kyō', length: 2, constituentKana: ['きょ', 'う'], phoneticProfile: { hasYouon: true }, tags: ['time', 'noun'] }, // today
    { kana: 'りょこう', romaji: 'ryokō', length: 3, constituentKana: ['りょ', 'こ', 'う'], phoneticProfile: { hasYouon: true }, tags: ['activity', 'noun'] },
    { kana: 'かいしゃ', romaji: 'kaisha', length: 3, constituentKana: ['か', 'い', 'しゃ'], phoneticProfile: { hasYouon: true }, tags: ['place', 'noun'] },
    { kana: 'びょういん', romaji: 'byōin', length: 4, constituentKana: ['びょ', 'う', 'い', 'ん'], phoneticProfile: { hasYouon: true, hasVoiced: true }, tags: ['place', 'noun'] },
    { kana: 'ちゃいろ', romaji: 'chairo', length: 3, constituentKana: ['ちゃ', 'い', 'ろ'], phoneticProfile: { hasYouon: true }, tags: ['color', 'noun'] },
    { kana: 'じしょ', romaji: 'jisho', length: 2, constituentKana: ['じ', 'しょ'], phoneticProfile: { hasYouon: true, hasVoiced: true }, tags: ['item', 'noun'] },

    // Phrases & Simple Verbs/Adjectives
    { kana: 'おはよう', romaji: 'ohayō', length: 4, constituentKana: ['お', 'は', 'よ', 'う'], isPhrase: true, tags: ['greeting'] },
    { kana: 'さようなら', romaji: 'sayōnara', length: 5, constituentKana: ['さ', 'よ', 'う', 'な', 'ら'], isPhrase: true, tags: ['greeting'] },
    { kana: 'ありがとう', romaji: 'arigatō', length: 5, constituentKana: ['あ', 'り', 'が', 'と', 'う'], phoneticProfile: { hasVoiced: true }, isPhrase: true, tags: ['phrase'] },
    { kana: 'こんにちは', romaji: 'konnichiwa', length: 5, constituentKana: ['こ', 'ん', 'に', 'ち', 'は'], isPhrase: true, tags: ['greeting'] },
    { kana: 'こんばんは', romaji: 'konbanwa', length: 5, constituentKana: ['こ', 'ん', 'ば', 'ん', 'は'], phoneticProfile: { hasVoiced: true }, isPhrase: true, tags: ['greeting'] },
    { kana: 'おやすみなさい', romaji: 'oyasuminasai', length: 7, constituentKana: ['お', 'や', 'す', 'み', 'な', 'さ', 'い'], isPhrase: true, tags: ['greeting'] },
    { kana: 'たべる', romaji: 'taberu', length: 3, constituentKana: ['た', 'べ', 'る'], tags: ['verb', 'action'] },
    { kana: 'たべます', romaji: 'tabemasu', length: 4, constituentKana: ['た', 'べ', 'ま', 'す'], tags: ['verb', 'polite-form', 'action'] },
    { kana: 'のみます', romaji: 'nomimasu', length: 4, constituentKana: ['の', 'み', 'ま', 'す'], tags: ['verb', 'polite-form', 'action'] },
    { kana: 'かわいい', romaji: 'kawaii', length: 4, constituentKana: ['か', 'わ', 'い', 'い'], tags: ['adjective', 'description'] },
    { kana: 'あつい', romaji: 'atsui', length: 3, constituentKana: ['あ', 'つ', 'い'], tags: ['adjective', 'description'] }, // hot (weather/object)

    // New Hiragana Words Start
    { kana: 'みず', romaji: 'mizu', length: 2, constituentKana: ['み', 'ず'], phoneticProfile: { hasVoiced: true }, tags: ['nature', 'noun', 'drink'] },
    { kana: 'そら', romaji: 'sora', length: 2, constituentKana: ['そ', 'ら'], tags: ['nature', 'noun'] },
    { kana: 'かわ', romaji: 'kawa', length: 2, constituentKana: ['か', 'わ'], tags: ['nature', 'noun'] },
    { kana: 'うみ', romaji: 'umi', length: 2, constituentKana: ['う', 'み'], tags: ['nature', 'noun'] },
    { kana: 'ほん', romaji: 'hon', length: 2, constituentKana: ['ほ', 'ん'], tags: ['item', 'noun', 'education'] },
    { kana: 'えいが', romaji: 'eiga', length: 3, constituentKana: ['え', 'い', 'が'], phoneticProfile: { hasVoiced: true }, tags: ['activity', 'entertainment', 'noun'] },
    { kana: 'おんがく', romaji: 'ongaku', length: 3, constituentKana: ['お', 'ん', 'が', 'く'], phoneticProfile: { hasVoiced: true }, tags: ['activity', 'entertainment', 'noun'] },
    { kana: 'でんしゃ', romaji: 'densha', length: 3, constituentKana: ['で', 'ん', 'しゃ'], phoneticProfile: { hasVoiced: true, hasYouon: true }, tags: ['transport', 'noun'] },
    { kana: 'しんぶん', romaji: 'shinbun', length: 3, constituentKana: ['し', 'ん', 'ぶ', 'ん'], phoneticProfile: { hasVoiced: true }, tags: ['item', 'media', 'noun'] },
    { kana: 'りょうり', romaji: 'ryōri', length: 3, constituentKana: ['りょ', 'う', 'り'], phoneticProfile: { hasYouon: true }, tags: ['activity', 'food', 'noun'] },
    { kana: 'くだもの', romaji: 'kudamono', length: 4, constituentKana: ['く', 'だ', 'も', 'の'], phoneticProfile: { hasVoiced: true }, tags: ['food', 'noun'] },
    { kana: 'やさい', romaji: 'yasai', length: 3, constituentKana: ['や', 'さ', 'い'], tags: ['food', 'noun'] },
    { kana: 'さかな', romaji: 'sakana', length: 3, constituentKana: ['さ', 'か', 'な'], tags: ['food', 'animal', 'noun'] },
    { kana: 'にく', romaji: 'niku', length: 2, constituentKana: ['に', 'く'], tags: ['food', 'noun'] },
    { kana: 'ぎんこう', romaji: 'ginkō', length: 4, constituentKana: ['ぎ', 'ん', 'こ', 'う'], phoneticProfile: { hasVoiced: true }, tags: ['place', 'noun'] },
    { kana: 'かいもの', romaji: 'kaimono', length: 4, constituentKana: ['か', 'い', 'も', 'の'], tags: ['activity', 'noun'] },
    { kana: 'しゅくだい', romaji: 'shukudai', length: 4, constituentKana: ['しゅ', 'く', 'だ', 'い'], phoneticProfile: { hasYouon: true, hasVoiced: true }, tags: ['activity', 'education', 'noun'] },
    { kana: 'べんきょう', romaji: 'benkyō', length: 4, constituentKana: ['べ', 'ん', 'きょ', 'う'], phoneticProfile: { hasVoiced: true, hasYouon: true }, tags: ['activity', 'education', 'noun'] },
    { kana: 'せんせい', romaji: 'sensei', length: 4, constituentKana: ['せ', 'ん', 'せ', 'い'], tags: ['people', 'education', 'noun'] },
    { kana: 'がくせい', romaji: 'gakusei', length: 4, constituentKana: ['が', 'く', 'せ', 'い'], phoneticProfile: { hasVoiced: true }, tags: ['people', 'education', 'noun'] },
    { kana: 'だいがく', romaji: 'daigaku', length: 4, constituentKana: ['だ', 'い', 'が', 'く'], phoneticProfile: { hasVoiced: true }, tags: ['place', 'education', 'noun'] },
    { kana: 'くすり', romaji: 'kusuri', length: 3, constituentKana: ['く', 'す', 'り'], tags: ['item', 'health', 'noun'] },
    { kana: 'てんき', romaji: 'tenki', length: 3, constituentKana: ['て', 'ん', 'き'], tags: ['nature', 'noun'] },
    { kana: 'せんしゅう', romaji: 'senshū', length: 4, constituentKana: ['せ', 'ん', 'しゅ', 'う'], phoneticProfile: { hasYouon: true }, tags: ['time', 'noun'] },
    { kana: 'きょうだい', romaji: 'kyōdai', length: 4, constituentKana: ['きょ', 'う', 'だ', 'い'], phoneticProfile: { hasYouon: true, hasVoiced: true }, tags: ['people', 'family', 'noun'] },
    { kana: 'おとうさん', romaji: 'otōsan', length: 5, constituentKana: ['お', 'と', 'う', 'さ', 'ん'], tags: ['people', 'family', 'noun'] },
    { kana: 'おかあさん', romaji: 'okāsan', length: 5, constituentKana: ['お', 'か', 'あ', 'さ', 'ん'], tags: ['people', 'family', 'noun'] },
    { kana: 'おにいさん', romaji: 'oniisan', length: 5, constituentKana: ['お', 'に', 'い', 'さ', 'ん'], tags: ['people', 'family', 'noun'] },
    { kana: 'おねえさん', romaji: 'onēsan', length: 5, constituentKana: ['お', 'ね', 'え', 'さ', 'ん'], tags: ['people', 'family', 'noun'] },
    { kana: 'ちいさい', romaji: 'chiisai', length: 4, constituentKana: ['ち', 'い', 'さ', 'い'], tags: ['size', 'adjective'] },
    { kana: 'たかい', romaji: 'takai', length: 3, constituentKana: ['た', 'か', 'い'], tags: ['price', 'height', 'adjective'] },
    { kana: 'やすい', romaji: 'yasui', length: 3, constituentKana: ['や', 'す', 'い'], tags: ['price', 'adjective'] },
    { kana: 'あたらしい', romaji: 'atarashii', length: 5, constituentKana: ['あ', 'た', 'ら', 'し', 'い'], tags: ['quality', 'adjective'] },
    { kana: 'ふるい', romaji: 'furui', length: 3, constituentKana: ['ふ', 'る', 'い'], tags: ['quality', 'adjective'] },
    { kana: 'げんき', romaji: 'genki', length: 3, constituentKana: ['げ', 'ん', 'き'], phoneticProfile: { hasVoiced: true }, tags: ['state', 'adjective', 'noun'] },
    { kana: 'はじめまして', romaji: 'hajimemashite', length: 6, constituentKana: ['は', 'じ', 'め', 'ま', 'し', 'て'], phoneticProfile: { hasVoiced: true }, isPhrase: true, tags: ['greeting'] },
    { kana: 'おねがいします', romaji: 'onegaishimasu', length: 7, constituentKana: ['お', 'ね', 'が', 'い', 'し', 'ま', 'す'], phoneticProfile: { hasVoiced: true }, isPhrase: true, tags: ['phrase'] },
    { kana: 'すみません', romaji: 'sumimasen', length: 5, constituentKana: ['す', 'み', 'ま', 'せ', 'ん'], isPhrase: true, tags: ['phrase', 'apology'] },
    // New Hiragana Words End

    // Plausible Non-Words (PNWs) - Keep proportion low
    { kana: 'あおえ', romaji: 'aoe', length: 3, constituentKana: ['あ', 'お', 'え'], isPlausibleNonWord: true, sourceWordKanaFromPlausible: 'あおい', derivationTypeForPlausible: 'vowelSwap', tags: ['pnw'] },
    { kana: 'せかいし', romaji: 'sekaishi', length: 4, constituentKana: ['せ', 'か', 'い', 'し'], isPlausibleNonWord: true, sourceWordKanaFromPlausible: 'せかい', derivationTypeForPlausible: 'addedMora', tags: ['pnw'] },
    { kana: 'きっふ', romaji: 'kiffu', length: 3, constituentKana: ['き', 'っ', 'ふ'], isPlausibleNonWord: true, sourceWordKanaFromPlausible: 'きっぷ', derivationTypeForPlausible: 'voicingError', phoneticProfile: { hasSokuon: true, hasHandakuten: false}, tags: ['pnw', 'sokuon'] },
    { kana: 'りょこうか', romaji: 'ryokōka', length: 4, constituentKana: ['りょ', 'こ', 'う', 'か'], isPlausibleNonWord: true, sourceWordKanaFromPlausible: 'りょこう', derivationTypeForPlausible: 'addedMora', phoneticProfile: { hasYouon: true }, tags: ['pnw', 'youon'] },
  ],
  [ScriptType.Katakana]: [
    // Basic & Chōonpu
    { kana: 'アイス', romaji: 'aisu', length: 3, constituentKana: ['ア', 'イ', 'ス'], tags: ['food', 'loanword'] },
    { kana: 'スキー', romaji: 'sukī', length: 3, constituentKana: ['ス', 'キ', 'ー'], phoneticProfile: { hasChoonpu: true }, tags: ['sport', 'loanword'] },
    { kana: 'コーヒー', romaji: 'kōhī', length: 4, constituentKana: ['コ', 'ー', 'ヒ', 'ー'], phoneticProfile: { hasChoonpu: true }, tags: ['food', 'drink', 'loanword'] },
    { kana: 'タクシー', romaji: 'takushī', length: 4, constituentKana: ['タ', 'ク', 'シ', 'ー'], phoneticProfile: { hasChoonpu: true }, tags: ['transport', 'loanword'] },
    { kana: 'カメラ', romaji: 'kamera', length: 3, constituentKana: ['カ', 'メ', 'ラ'], tags: ['item', 'tech', 'loanword'] },
    { kana: 'テレビ', romaji: 'terebi', length: 3, constituentKana: ['テ', 'レ', 'ビ'], phoneticProfile: { hasVoiced: true }, tags: ['item', 'tech', 'loanword'] },
    { kana: 'パン', romaji: 'pan', length: 2, constituentKana: ['パ', 'ン'], phoneticProfile: { hasHandakuten: true }, tags: ['food', 'loanword'] },
    { kana: 'ノート', romaji: 'nōto', length: 3, constituentKana: ['ノ', 'ー', 'ト'], phoneticProfile: { hasChoonpu: true }, tags: ['item', 'stationery', 'loanword'] },
    { kana: 'バス', romaji: 'basu', length: 2, constituentKana: ['バ', 'ス'], phoneticProfile: { hasVoiced: true }, tags: ['transport', 'loanword'] },
    { kana: 'スポーツ', romaji: 'supōtsu', length: 4, constituentKana: ['ス', 'ポ', 'ー', 'ツ'], phoneticProfile: { hasHandakuten: true, hasChoonpu: true }, tags: ['activity', 'loanword'] },
    { kana: 'ホテル', romaji: 'hoteru', length: 3, constituentKana: ['ホ', 'テ', 'ル'], tags: ['place', 'loanword'] },
    { kana: 'メニュー', romaji: 'menyū', length: 4, constituentKana: ['メ', 'ニュ', 'ー'], phoneticProfile: { hasYouon: true, hasChoonpu: true}, tags:['item', 'food', 'loanword']},

    // Sokuon & More Complex Yōon/Extended
    { kana: 'ベッド', romaji: 'beddo', length: 3, constituentKana: ['ベ', 'ッ', 'ド'], phoneticProfile: { hasVoiced: true, hasSokuon: true }, tags: ['item', 'furniture', 'loanword'] },
    { kana: 'サッカー', romaji: 'sakkā', length: 4, constituentKana: ['サ', 'ッ', 'カ', 'ー'], phoneticProfile: { hasSokuon: true, hasChoonpu: true }, tags: ['sport', 'loanword'] },
    { kana: 'サンドイッチ', romaji: 'sandoitchi', length: 6, constituentKana: ['サ', 'ン', 'ド', 'イ', 'ッ', 'チ'], phoneticProfile: { hasVoiced: true, hasSokuon: true }, tags: ['food', 'loanword'] },
    { kana: 'パーティー', romaji: 'pātī', length: 4, constituentKana: ['パ', 'ー', 'ティ', 'ー'], phoneticProfile: { hasHandakuten: true, hasChoonpu: true, hasYouon: true }, tags: ['event', 'loanword'] },
    { kana: 'フォーク', romaji: 'fōku', length: 3, constituentKana: ['フォ', 'ー', 'ク'], phoneticProfile: { hasYouon: true, hasChoonpu: true }, tags: ['item', 'food', 'loanword'] },
    { kana: 'チェック', romaji: 'chekku', length: 3, constituentKana: ['チェ', 'ッ', 'ク'], phoneticProfile: { hasYouon: true, hasSokuon: true }, tags:['action', 'loanword']},
    { kana: 'チョコレート', romaji: 'chokorēto', length: 6, constituentKana: ['チョ', 'コ', 'レ', 'ー', 'ト'], phoneticProfile: {hasYouon: true, hasChoonpu: true}, tags:['food', 'loanword']},
    { kana: 'ジュース', romaji: 'jūsu', length: 3, constituentKana: ['ジュ', 'ー', 'ス'], phoneticProfile: {hasYouon: true, hasVoiced: true, hasChoonpu: true}, tags: ['food', 'drink', 'loanword']},
    { kana: 'ワイシャツ', romaji: 'waishatsu', length: 4, constituentKana: ['ワ', 'イ', 'シャ', 'ツ'], phoneticProfile: {hasYouon: true}, tags: ['item', 'clothing', 'loanword']},
    { kana: 'コンピュータ', romaji: 'konpyūta', length: 6, constituentKana: ['コ', 'ン', 'ピュ', 'ー', 'タ'], phoneticProfile: {hasHandakuten: true, hasYouon: true, hasChoonpu: true}, tags: ['item', 'tech', 'loanword']},

    // New Katakana Words Start
    { kana: 'トマト', romaji: 'tomato', length: 3, constituentKana: ['ト', 'マ', 'ト'], tags: ['food', 'vegetable', 'loanword'] },
    { kana: 'オレンジ', romaji: 'orenji', length: 4, constituentKana: ['オ', 'レ', 'ン', 'ジ'], phoneticProfile: { hasVoiced: true }, tags: ['food', 'fruit', 'loanword'] },
    { kana: 'バナナ', romaji: 'banana', length: 3, constituentKana: ['バ', 'ナ', 'ナ'], phoneticProfile: { hasVoiced: true }, tags: ['food', 'fruit', 'loanword'] },
    { kana: 'レストラン', romaji: 'resutoran', length: 5, constituentKana: ['レ', 'ス', 'ト', 'ラ', 'ン'], tags: ['place', 'food', 'loanword'] },
    { kana: 'スーパー', romaji: 'sūpā', length: 4, constituentKana: ['ス', 'ー', 'パ', 'ー'], phoneticProfile: { hasChoonpu: true, hasHandakuten: true }, tags: ['place', 'shop', 'loanword'] },
    { kana: 'アパート', romaji: 'apāto', length: 4, constituentKana: ['ア', 'パ', 'ー', 'ト'], phoneticProfile: { hasChoonpu: true, hasHandakuten: true }, tags: ['place', 'home', 'loanword'] },
    { kana: 'エレベーター', romaji: 'erebētā', length: 6, constituentKana: ['エ', 'レ', 'ベ', 'ー', 'タ', 'ー'], phoneticProfile: { hasVoiced: true, hasChoonpu: true }, tags: ['item', 'place', 'loanword'] },
    { kana: 'パソコン', romaji: 'pasokon', length: 4, constituentKana: ['パ', 'ソ', 'コ', 'ン'], phoneticProfile: { hasHandakuten: true }, tags: ['item', 'tech', 'loanword'] },
    { kana: 'インターネット', romaji: 'intānetto', length: 7, constituentKana: ['イ', 'ン', 'タ', 'ー', 'ネ', 'ッ', 'ト'], phoneticProfile: { hasChoonpu: true, hasSokuon: true }, tags: ['tech', 'loanword'] },
    { kana: 'ゲーム', romaji: 'gēmu', length: 3, constituentKana: ['ゲ', 'ー', 'ム'], phoneticProfile: { hasVoiced: true, hasChoonpu: true }, tags: ['activity', 'entertainment', 'loanword'] },
    { kana: 'ラジオ', romaji: 'rajio', length: 3, constituentKana: ['ラ', 'ジ', 'オ'], phoneticProfile: { hasVoiced: true }, tags: ['item', 'tech', 'media', 'loanword'] },
    { kana: 'クラス', romaji: 'kurasu', length: 3, constituentKana: ['ク', 'ラ', 'ス'], tags: ['place', 'education', 'loanword'] },
    { kana: 'シャワー', romaji: 'shawā', length: 3, constituentKana: ['シャ', 'ワ', 'ー'], phoneticProfile: { hasYouon: true, hasChoonpu: true }, tags: ['item', 'home', 'loanword'] },
    { kana: 'チーズ', romaji: 'chīzu', length: 3, constituentKana: ['チ', 'ー', 'ズ'], phoneticProfile: { hasChoonpu: true, hasVoiced: true }, tags: ['food', 'loanword'] },
    { kana: 'ワイン', romaji: 'wain', length: 3, constituentKana: ['ワ', 'イ', 'ン'], tags: ['food', 'drink', 'loanword'] },
    { kana: 'ビール', romaji: 'bīru', length: 3, constituentKana: ['ビ', 'ー', 'ル'], phoneticProfile: { hasVoiced: true, hasChoonpu: true }, tags: ['food', 'drink', 'loanword'] },
    { kana: 'ペン', romaji: 'pen', length: 2, constituentKana: ['ペ', 'ン'], phoneticProfile: { hasHandakuten: true }, tags: ['item', 'stationery', 'loanword'] },
    { kana: 'ドア', romaji: 'doa', length: 2, constituentKana: ['ド', 'ア'], phoneticProfile: { hasVoiced: true }, tags: ['item', 'home', 'loanword'] },
    { kana: 'バスケットボール', romaji: 'basukettobōru', length: 9, constituentKana: ['バ', 'ス', 'ケ', 'ッ', 'ト', 'ボ', 'ー', 'ル'], phoneticProfile: { hasVoiced: true, hasSokuon: true, hasChoonpu: true }, tags: ['sport', 'loanword'] },
    { kana: 'テニス', romaji: 'tenisu', length: 3, constituentKana: ['テ', 'ニ', 'ス'], tags: ['sport', 'loanword'] },
    { kana: 'アメリカ', romaji: 'amerika', length: 4, constituentKana: ['ア', 'メ', 'リ', 'カ'], tags: ['place', 'country', 'loanword'] },
    { kana: 'フランス', romaji: 'furansu', length: 4, constituentKana: ['フ', 'ラ', 'ン', 'ス'], tags: ['place', 'country', 'loanword'] },
    { kana: 'ティーシャツ', romaji: 'tīshatsu', length: 4, constituentKana: ['ティ', 'ー', 'シャ', 'ツ'], phoneticProfile: { hasYouon: true, hasChoonpu: true }, tags: ['item', 'clothing', 'loanword'] },
    { kana: 'セーター', romaji: 'sētā', length: 4, constituentKana: ['セ', 'ー', 'タ', 'ー'], phoneticProfile: { hasChoonpu: true }, tags: ['item', 'clothing', 'loanword'] },
    { kana: 'スカート', romaji: 'sukāto', length: 4, constituentKana: ['ス', 'カ', 'ー', 'ト'], phoneticProfile: { hasChoonpu: true }, tags: ['item', 'clothing', 'loanword'] },
    { kana: 'クリスマス', romaji: 'kurisumasu', length: 5, constituentKana: ['ク', 'リ', 'ス', 'マ', 'ス'], tags: ['event', 'loanword'] },
    { kana: 'カレンダー', romaji: 'karendā', length: 5, constituentKana: ['カ', 'レ', 'ン', 'ダ', 'ー'], phoneticProfile: { hasVoiced: true, hasChoonpu: true }, tags: ['item', 'loanword'] },
    { kana: 'キロメートル', romaji: 'kiromētoru', length: 6, constituentKana: ['キ', 'ロ', 'メ', 'ー', 'ト', 'ル'], phoneticProfile: { hasChoonpu: true }, tags: ['unit', 'loanword'] },
    { kana: 'グラム', romaji: 'guramu', length: 3, constituentKana: ['グ', 'ラ', 'ム'], phoneticProfile: { hasVoiced: true }, tags: ['unit', 'loanword'] },
    // New Katakana Words End
    
    // Plausible Non-Words (PNWs) - Katakana
    { kana: 'カメラン', romaji: 'kameran', length: 4, constituentKana: ['カ', 'メ', 'ラ', 'ン'], isPlausibleNonWord: true, sourceWordKanaFromPlausible: 'カメラ', derivationTypeForPlausible: 'addedMora', tags: ['pnw', 'loanword'] },
    { kana: 'スポッツ', romaji: 'supottsu', length: 4, constituentKana: ['ス', 'ポ', 'ッ', 'ツ'], isPlausibleNonWord: true, sourceWordKanaFromPlausible: 'スポーツ', derivationTypeForPlausible: 'choonpuError', phoneticProfile: { hasHandakuten: true, hasSokuon: true }, tags: ['pnw', 'loanword', 'sokuon'] },
    { kana: 'テービ', romaji: 'tēbi', length: 3, constituentKana: ['テ', 'ー', 'ビ'], phoneticProfile: {hasChoonpu: true, hasVoiced: true}, isPlausibleNonWord: true, sourceWordKanaFromPlausible: 'テレビ', derivationTypeForPlausible: 'visualSwap', tags: ['pnw', 'loanword', 'choonpu'] },
    { kana: 'フーク', romaji: 'fūku', length: 2, constituentKana: ['フ', 'ー', 'ク'], phoneticProfile: {hasChoonpu: true}, isPlausibleNonWord: true, sourceWordKanaFromPlausible: 'フォーク', derivationTypeForPlausible: 'youonError', tags: ['pnw', 'loanword', 'choonpu'] },
  ],
};

export const KANA_SIMILARITIES_DATA: { [key in ScriptType]: KanaSimilarities } = {
  [ScriptType.Hiragana]: {
    'あ': [{ similarKana: 'お', strength: 0.7 }, { similarKana: 'め', strength: 0.6 }, { similarKana: 'ぬ', strength: 0.5 }],
    'い': [{ similarKana: 'り', strength: 0.8 }, { similarKana: 'こ', strength: 0.4 }, {similarKana: 'け', strength: 0.3}],
    'う': [{ similarKana: 'つ', strength: 0.6 }, { similarKana: 'ら', strength: 0.5 }, { similarKana: 'る', strength: 0.4}, {similarKana: 'ふ', strength: 0.5}],
    'え': [{ similarKana: 'へ', strength: 0.7 }, { similarKana: 'れ', strength: 0.5 }, {similarKana: 'ん', strength: 0.4}],
    'お': [{ similarKana: 'あ', strength: 0.7 }, { similarKana: 'む', strength: 0.5 }, {similarKana: 'を', strength: 0.6}],
    'か': [{ similarKana: 'が', strength: 0.9 }, { similarKana: 'ち', strength: 0.3 }, {similarKana: 'こ', strength: 0.3}],
    'き': [{ similarKana: 'ぎ', strength: 0.9 }, { similarKana: 'さ', strength: 0.5 }],
    'く': [{ similarKana: 'ぐ', strength: 0.9 }, { similarKana: 'へ', strength: 0.6 }, {similarKana: 'う', strength: 0.4}],
    'け': [{ similarKana: 'げ', strength: 0.9 }, { similarKana: 'は', strength: 0.5 }, {similarKana: 'い', strength: 0.3}],
    'こ': [{ similarKana: 'ご', strength: 0.9 }, { similarKana: 'に', strength: 0.6 }, {similarKana: 'い', strength: 0.4}],
    'さ': [{ similarKana: 'ざ', strength: 0.9 }, { similarKana: 'ち', strength: 0.7 }, { similarKana: 'き', strength: 0.6 }],
    'し': [{ similarKana: 'じ', strength: 0.9 }, { similarKana: 'つ', strength: 0.7 }, {similarKana: 'も', strength: 0.5}],
    'す': [{ similarKana: 'ず', strength: 0.9 }, { similarKana: 'ぬ', strength: 0.5 }, {similarKana: 'お', strength: 0.4}],
    'せ': [{ similarKana: 'ぜ', strength: 0.9 }, {similarKana: 'そ', strength: 0.3}],
    'そ': [{ similarKana: 'ぞ', strength: 0.9 }, { similarKana: 'ろ', strength: 0.6 }, {similarKana: 'せ', strength: 0.3}],
    'た': [{ similarKana: 'だ', strength: 0.9 }, { similarKana: 'な', strength: 0.5 }, {similarKana: 'に', strength: 0.4}],
    'ち': [{ similarKana: 'ぢ', strength: 0.9 }, { similarKana: 'さ', strength: 0.7 }, { similarKana: 'ら', strength: 0.6 }],
    'つ': [{ similarKana: 'づ', strength: 0.9 }, { similarKana: 'う', strength: 0.6 }, { similarKana: 'し', strength: 0.7, comment:"し (shi) vs つ (tsu)"}, {similarKana: 'っ', strength: 0.8}],
    'て': [{ similarKana: 'で', strength: 0.9 }, {similarKana: 'と', strength: 0.4}],
    'と': [{ similarKana: 'ど', strength: 0.9 }, {similarKana: 'て', strength: 0.4}],
    'な': [{ similarKana: 'た', strength: 0.5 }, {similarKana: 'ぬ', strength: 0.4}],
    'に': [{ similarKana: 'こ', strength: 0.6 }, {similarKana: 'た', strength: 0.4}],
    'ぬ': [{ similarKana: 'め', strength: 0.7 }, { similarKana: 'あ', strength: 0.6 }, {similarKana: 'す', strength: 0.5}],
    'ね': [{ similarKana: 'れ', strength: 0.8 }, { similarKana: 'わ', strength: 0.7 }],
    'の': [{similarKana: 'め', strength: 0.3}],
    'は': [{ similarKana: 'ば', strength: 0.9 }, { similarKana: 'ぱ', strength: 0.85 }, { similarKana: 'ほ', strength: 0.6 }, {similarKana: 'け', strength: 0.5}],
    'ひ': [{ similarKana: 'び', strength: 0.9 }, { similarKana: 'ぴ', strength: 0.85 }],
    'ふ': [{ similarKana: 'ぶ', strength: 0.9 }, { similarKana: 'ぷ', strength: 0.85 }, {similarKana: 'う', strength: 0.5}],
    'へ': [{ similarKana: 'べ', strength: 0.9 }, { similarKana: 'ぺ', strength: 0.85 }, {similarKana: 'え', strength: 0.7}, {similarKana: 'く', strength: 0.6}],
    'ほ': [{ similarKana: 'ぼ', strength: 0.9 }, { similarKana: 'ぽ', strength: 0.85 }, {similarKana: 'は', strength: 0.6}],
    'ま': [{similarKana: 'も', strength: 0.4}],
    'め': [{ similarKana: 'ぬ', strength: 0.7 }, { similarKana: 'あ', strength: 0.6 }, {similarKana: 'の', strength: 0.3}],
    'も': [{similarKana: 'し', strength: 0.5}, {similarKana: 'ま', strength: 0.4}],
    'る': [{ similarKana: 'ろ', strength: 0.8 }, { similarKana: 'う', strength: 0.5 }, {similarKana: 'る', strength: 0.4}],
    'れ': [{ similarKana: 'ね', strength: 0.8 }, { similarKana: 'わ', strength: 0.7 }, {similarKana: 'え', strength: 0.5}],
    'ろ': [{ similarKana: 'る', strength: 0.8 }, {similarKana: 'そ', strength: 0.6}],
    'わ': [{ similarKana: 'ね', strength: 0.7 }, { similarKana: 'れ', strength: 0.7 }],
    'を': [{similarKana: 'お', strength: 0.6}],
    'ん': [{similarKana: 'え', strength: 0.4}],
    'っ': [{similarKana: 'つ', strength: 0.8}],
  },
  [ScriptType.Katakana]: {
    'ア': [{ similarKana: 'マ', strength: 0.7 }, { similarKana: 'ヤ', strength: 0.6 }, {similarKana: 'ヲ', strength: 0.3}],
    'イ': [{ similarKana: 'リ', strength: 0.6 }, {similarKana: 'ニ', strength: 0.5}],
    'ウ': [{ similarKana: 'ワ', strength: 0.7 }, { similarKana: 'フ', strength: 0.6 }, {similarKana: 'ラ', strength: 0.4}],
    'エ': [{ similarKana: 'ユ', strength: 0.5}, {similarKana: 'エ', strength: 0.4}], // ユ vs エ is a common one
    'オ': [{ similarKana: 'ヲ', strength: 0.6}, {similarKana: '才', strength: 0.4}], // 才 is not kana but similar
    'カ': [{ similarKana: 'ガ', strength: 0.9 }, {similarKana: 'ケ', strength: 0.4}],
    'キ': [{ similarKana: 'ギ', strength: 0.9 }, {similarKana: 'ケ', strength: 0.3}],
    'ク': [{ similarKana: 'グ', strength: 0.9 }, { similarKana: 'ワ', strength: 0.6 }, { similarKana: 'ケ', strength: 0.5 }, {similarKana: 'タ', strength: 0.6}],
    'ケ': [{ similarKana: 'ゲ', strength: 0.9 }, {similarKana: 'カ', strength: 0.4}, {similarKana: 'ク', strength: 0.5}],
    'コ': [{ similarKana: 'ゴ', strength: 0.9 }, {similarKana: 'ニ', strength: 0.5}],
    'サ': [{ similarKana: 'ザ', strength: 0.9 }, {similarKana: 'セ', strength: 0.4}],
    'シ': [{ similarKana: 'ジ', strength: 0.9 }, { similarKana: 'ツ', strength: 0.9 }, { similarKana: 'ン', strength: 0.8 }],
    'ス': [{ similarKana: 'ズ', strength: 0.9 }, {similarKana: 'ヌ', strength: 0.5}],
    'セ': [{ similarKana: 'ゼ', strength: 0.9 }, {similarKana: 'サ', strength: 0.4}],
    'ソ': [{ similarKana: 'ゾ', strength: 0.9 }, { similarKana: 'ン', strength: 0.8 }, { similarKana: 'ツ', strength: 0.7 }],
    'タ': [{ similarKana: 'ダ', strength: 0.9 }, { similarKana: 'ヌ', strength: 0.5 }, { similarKana: 'ク', strength: 0.6 }],
    'チ': [{ similarKana: 'ヂ', strength: 0.9 }, {similarKana: 'テ', strength: 0.4}],
    'ツ': [{ similarKana: 'ヅ', strength: 0.9 }, { similarKana: 'シ', strength: 0.9 }, { similarKana: 'ン', strength: 0.8 }, { similarKana: 'ソ', strength: 0.7 }, {similarKana: 'ッ', strength: 0.8}],
    'テ': [{ similarKana: 'デ', strength: 0.9 }, {similarKana: 'チ', strength: 0.4}],
    'ト': [{ similarKana: 'ド', strength: 0.9 }],
    'ナ': [{similarKana: 'メ', strength: 0.4}],
    'ニ': [{similarKana: 'コ', strength: 0.5}, {similarKana: 'イ', strength: 0.5}],
    'ヌ': [{similarKana: 'ス', strength: 0.5}, {similarKana: 'タ', strength: 0.5}],
    'ネ': [{similarKana: 'ホ', strength: 0.4}], // Visually quite different but sometimes confused
    'ノ': [],
    'ハ': [{ similarKana: 'バ', strength: 0.9 }, { similarKana: 'パ', strength: 0.85 }],
    'ヒ': [{ similarKana: 'ビ', strength: 0.9 }, { similarKana: 'ピ', strength: 0.85 }],
    'フ': [{ similarKana: 'ブ', strength: 0.9 }, { similarKana: 'プ', strength: 0.85 }, {similarKana: 'ウ', strength: 0.6}, {similarKana: 'ワ', strength: 0.5}],
    'ヘ': [{ similarKana: 'ベ', strength: 0.9 }, { similarKana: 'ペ', strength: 0.85 }],
    'ホ': [{ similarKana: 'ボ', strength: 0.9 }, { similarKana: 'ポ', strength: 0.85 }, {similarKana: 'ネ', strength: 0.4}],
    'マ': [{similarKana: 'ア', strength: 0.7}],
    'メ': [{similarKana: 'ナ', strength: 0.4}],
    'ヤ': [{similarKana: 'ア', strength: 0.6}],
    'ユ': [{similarKana: 'エ', strength: 0.5}], // Common confusion ユ vs エ
    'リ': [{similarKana: 'イ', strength: 0.6}],
    'ル': [{similarKana: 'レ', strength: 0.5}],
    'レ': [{similarKana: 'ル', strength: 0.5}],
    'ワ': [{similarKana: 'ウ', strength: 0.7}, {similarKana: 'ク', strength: 0.6}, {similarKana: 'フ', strength: 0.5}],
    'ヲ': [{similarKana: 'ア', strength: 0.3}, {similarKana: 'オ', strength: 0.6}],
    'ン': [{ similarKana: 'ソ', strength: 0.8 }, { similarKana: 'シ', strength: 0.7 }, { similarKana: 'ツ', strength: 0.7 }],
    'ッ': [{similarKana: 'ツ', strength: 0.8}],
    'ー': [], // Chōonpu is quite distinct
  },
};
